### ISSUE TITLE
DemoServer stack traces end with a lot of bolierplate

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#2168]
```
demo-server[4802]: server error: #015                        #015#011Error Trace:#011
demo-server[4802]: #015#011Error:#011#011Received unexpected error "open /home/ec2-user/demo-server/db/056869.ldb: too many open files"
demo-server[4802]: #015
demo-server[4802]: goroutine 345063 [running]:
demo-server[4802]: runtime/debug.Stack(0x0, 0x0, 0x0)
demo-server[4802]: #011/usr/local/go/src/runtime/debug/stack.go:24 +0x80
demo-server[4802]: runtime/debug.PrintStack()
demo-server[4802]: #011/usr/local/go/src/runtime/debug/stack.go:16 +0x18
demo-server[4802]: main.panicHandler(0x7ff8a26b6db0, 0xc82d6f3ba0, 0xc82518db20, 0x877860, 0xc82db85380)
demo-server[4802]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/samples/go/demo-server/web_server.go:137 +0x1cf
demo-server[4802]: github.com/attic-labs/noms/vendor/github.com/julienschmidt/httprouter.(*Router).recv(0xc82000a680, 0x7ff8a26b6db0, 0xc82d6f3ba0, 0xc82518db20)
demo-server[4802]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/vendor/github.com/julienschmidt/httprouter/router.go:273 +0x70
demo-server[4802]: panic(0x877860, 0xc82db85380)
demo-server[4802]: #011/usr/local/go/src/runtime/panic.go:426 +0x4e9
demo-server[4802]: github.com/attic-labs/noms/go/d.recoverWrappedTypes(0xc82482d678, 0x0, 0x0, 0x0)
demo-server[4802]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/go/d/try.go:146 +0xf2
demo-server[4802]: panic(0x877860, 0xc82db85380)
demo-server[4802]: #011/usr/local/go/src/runtime/panic.go:426 +0x4e9
demo-server[4802]: github.com/attic-labs/noms/go/d.panicker.Errorf(0xabafc0, 0x21, 0xc830d37440, 0x3, 0x3)
demo-server[4802]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/go/d/try.go:25 +0x9e
demo-server[4802]: github.com/attic-labs/noms/go/d.(*panicker).Errorf(0xd520d8, 0xabafc0, 0x21, 0xc830d37440, 0x3, 0x3)
demo-server[4802]: #011<autogenerated>:2 +0xbf
demo-server[4802]: github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.Fail(0x7ff8a26a71e8, 0xd520d8, 0xc826c45ec0, 0x5e, 0x0, 0x0, 0x0, 0xc824b476c0)
demo-server[4802]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertions.go:225 +0x5cb
demo-server[4802]: github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.NoError(0x7ff8a26a71e8, 0xd520d8, 0x7ff8a04ab128, 0xc82ce908a0, 0x0, 0x0, 0x0, 0x0)
demo-server[4802]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertions.go:839 +0x18e
demo-server[4802]: github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.(*Assertions).NoError(0xc820010610, 0x7ff8a04ab128, 0xc82ce908a0, 0x0, 0x0, 0x0, 0x0)
demo-server[4802]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertion_forward.go:205 +0x5f
demo-server[4802]: github.com/attic-labs/noms/go/chunks.(*internalLevelDBStore).getByKey(0xc82000a5c0, 0xc82f6d27e0, 0x24, 0x24, 0x25c7760592df760f, 0x2c142d88b52aaa29, 0xc8e6adb7c3, 0x0, 0x0, 0x0, ...)
```

It's not until the last line that the place the error came from actually shows up. Not sure what we can do about this, but I figured I'd make a record of it for future reference :-)

**Comment by cmasone-attic** [comment]
Bleh. There really isn't much to be done, here.
