### ISSUE TITLE
Crash when doing `noms log`  in a dataset

### ISSUE THREAD

**Issue by vinibaggio** [attic-labs/noms#2278]
As I shared in Slack, here's the crash I have when doing `noms log` on a dataset. "Goals" is a Map that might or might not be present in a List in a Struct:

```
▶noms log /tmp/tmp::dataset
        Error Trace:
        Error:          Struct has no field "Goals"


goroutine 45 [running]:
panic(0x4c7c00, 0xc821177030)
        /usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:481 +0x3e6
github.com/attic-labs/noms/go/d.panicker.Errorf(0x72f020, 0x21, 0xc820350c00, 0x3, 0x3)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/go/d/try.go:25 +0x9e
github.com/attic-labs/noms/go/d.(*panicker).Errorf(0x9ed7a8, 0x72f020, 0x21, 0xc820350c00, 0x3, 0x3)
        <autogenerated>:2 +0xbf
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.Fail(0xe541e8, 0x9ed7a8, 0xc82034c940, 0x1b, 0x0, 0x0, 0x0, 0x1b)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertions.go:225 +0x5cb
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.(*Assertions).Fail(0xc820012630, 0xc82034c940, 0x1b, 0x0, 0x0, 0x0, 0x1b)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertion_forward.go:101 +0x5f
github.com/attic-labs/noms/go/types.Struct.Get(0xc821176320, 0x1, 0x1, 0xc82117c480, 0xc82034c200, 0xc821174ca8, 0x5, 0x0, 0x0)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/go/types/struct.go:110 +0x2db
github.com/attic-labs/noms/cmd/noms/diff.diffStructs.func3(0xe60438, 0xc821176c20, 0x0, 0x0)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/cmd/noms/diff/diff.go:124 +0x91
github.com/attic-labs/noms/cmd/noms/diff.diffOrdered(0x1c40800, 0xc820070270, 0xc82034c860, 0x2, 0x2, 0x7b5e30, 0xc8203b2000, 0x7b5e18, 0xc8203508a0, 0xc8203508d0, ...)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/cmd/noms/diff/diff.go:163 +0x3c7
github.com/attic-labs/noms/cmd/noms/diff.diffStructs(0x1c40800, 0xc820070270, 0xc82034c860, 0x2, 0x2, 0xc821176320, 0x1, 0x1, 0xc82117c480, 0xc82034c200, ...)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/cmd/noms/diff/diff.go:126 +0x2e7
github.com/attic-labs/noms/cmd/noms/diff.diff(0x1c40800, 0xc820070270, 0xc82034c860, 0x2, 0x2, 0xe60438, 0xc821176310, 0xe607a0, 0xc8203501e0, 0xe607a0, ...)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/cmd/noms/diff/diff.go:43 +0x6e7
github.com/attic-labs/noms/cmd/noms/diff.diffOrdered(0x1c40800, 0xc820070270, 0xc8201841d0, 0x1, 0x1, 0x7b5e40, 0xc82000f300, 0x7b5df0, 0xc8202465e0, 0xc820246600, ...)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/cmd/noms/diff/diff.go:168 +0x63b
github.com/attic-labs/noms/cmd/noms/diff.diffMaps(0x1c40800, 0xc820070270, 0xc8201841d0, 0x1, 0x1, 0xe60a30, 0xc82017c880, 0xc82022cfc0, 0xe60a30, 0xc82117df00, ...)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/cmd/noms/diff/diff.go:116 +0x1b7
github.com/attic-labs/noms/cmd/noms/diff.diff(0x1c40800, 0xc820070270, 0xc8201841d0, 0x1, 0x1, 0xe60438, 0xc82017ef90, 0xe60538, 0xc82022cfe0, 0xe60538, ...)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/cmd/noms/diff/diff.go:39 +0x396
github.com/attic-labs/noms/cmd/noms/diff.diffOrdered(0x1c40800, 0xc820070270, 0xc82019b670, 0x0, 0x0, 0x7b5e40, 0xc82000f280, 0x7b5df0, 0xc820246220, 0xc820246240, ...)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/cmd/noms/diff/diff.go:168 +0x63b
github.com/attic-labs/noms/cmd/noms/diff.diffMaps(0x1c40800, 0xc820070270, 0xc82019b670, 0x0, 0x0, 0xe604d8, 0xc8221c32c0, 0xc82022d2a0, 0xe604d8, 0xc8200fb380, ...)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/cmd/noms/diff/diff.go:116 +0x1b7
github.com/attic-labs/noms/cmd/noms/diff.diff(0x1c40800, 0xc820070270, 0xc82019b670, 0x0, 0x0, 0x0, 0x0, 0xe60538, 0xc82022d2c0, 0xe60538, ...)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/cmd/noms/diff/diff.go:39 +0x396
github.com/attic-labs/noms/cmd/noms/diff.Diff(0x1c40800, 0xc820070270, 0xe60538, 0xc82022d2c0, 0xe60538, 0xc820123080, 0x0, 0x0)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/cmd/noms/diff/diff.go:26 +0xdc
main.writeDiffLines(0x694e1934e3985d23, 0xaa1a8ab101e2427c, 0xcadb2b56, 0xd, 0xc820075540, 0xc8201236c0, 0xc8200fab40, 0x3, 0x3, 0xc820074e80, ...)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/cmd/noms/noms_log.go:268 +0x628
main.printCommit(0x694e1934e3985d23, 0xaa1a8ab101e2427c, 0xcadb2b56, 0xd, 0xc820075540, 0xc8201236c0, 0xc8200fab40, 0x3, 0x3, 0xc820074e80, ...)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/cmd/noms/noms_log.go:163 +0x1113
main.runLog.func1(0x65fd00, 0xc8200da2c0, 0x0, 0x0)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/cmd/noms/noms_log.go:85 +0x155
github.com/attic-labs/noms/go/util/orderedparallel.New.func3(0xc82006e300, 0xc8201236e0, 0xc8200fb5c0, 0xc821175ed0, 0xc821175ee0, 0xc821175ed8, 0xc82006e420)
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/go/util/orderedparallel/ordered_parallel.go:51 +0x9f
created by github.com/attic-labs/noms/go/util/orderedparallel.New
        /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/go/util/orderedparallel/ordered_parallel.go:61 +0x2e7
```

**Comment by vinibaggio** [comment]
A bit more context on the data model:

`Model` is  a struct that may contain a field called `Goals` (not all of them do).
`Goals` is a List of Maps with fields `string: Title` and `string: Content`.

**Comment by vinibaggio** [comment]
@kalman thank you!

**Comment by kalman** [comment]
Good catch!
