### ISSUE TITLE
CLI tour csv-import fails

### ISSUE THREAD

**Issue by vsivsi** [attic-labs/noms#2490]
Hi! noms seems like a very cool and useful project, but I ran into difficulties almost immediately when running through the CLI tour. 

I installed and built noms per the instructions on the install page.

Everything in the tour works great until the `noms sync` section.  Then this:

```sh
> noms sync http://demo.noms.io/cli-tour::sf-film-locations /tmp/noms::films
> noms ds /tmp/noms
films

# So far so good...

> go install github.com/attic-labs/noms/samples/go/csv/...
> csv-export /tmp/noms::films > /tmp/film-locations.csv

# Great!  Now make no edits and just re-import...

> csv-import --column-types=String,String,String,String,String,String,String,Number,String,String,String \
    /tmp/film-locations.csv /tmp/noms::films

        Error Trace:    s)...panic: 
        Error:		Error parsing value for column 'Age': Could not parse ' 49' into number (strconv.ParseFloat: parsing " 49": invalid syntax)

goroutine 1 [running]:
panic(0x30d9a0, 0xc42117c8b0)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
github.com/attic-labs/noms/go/d.panicker.Errorf(0x397c5a, 0x21, 0xc420114ed0, 0x3, 0x3)
	/Users/vsi/work/src/github.com/attic-labs/noms/go/d/try.go:26 +0xa6
github.com/attic-labs/noms/go/d.(*panicker).Errorf(0x555908, 0x397c5a, 0x21, 0xc420114ed0, 0x3, 0x3)
	<autogenerated>:2 +0x7e
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.Fail(0x516b80, 0x555908, 0xc4200b4300, 0x7b, 0x0, 0x0, 0x0, 0xc42117e000)
	/Users/vsi/work/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertions.go:225 +0x510
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.(*Assertions).Fail(0xc420078550, 0xc4200b4300, 0x7b, 0x0, 0x0, 0x0, 0x7b)
	/Users/vsi/work/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertion_forward.go:101 +0x69
github.com/attic-labs/noms/samples/go/csv.readFieldsFromRow(0xc42117a440, 0x3, 0x4, 0xc420077400, 0x3, 0x4, 0xc4201030e0, 0x3, 0x3, 0xc42117c538, ...)
	/Users/vsi/work/src/github.com/attic-labs/noms/samples/go/csv/read.go:144 +0x2fe
github.com/attic-labs/noms/samples/go/csv.ReadToList(0xc42011a5a0, 0x38d43c, 0x3, 0xc420077400, 0x3, 0x4, 0xc420112787, 0x3, 0x3, 0x6bdaa0, ...)
	/Users/vsi/work/src/github.com/attic-labs/noms/samples/go/csv/read.go:103 +0x23f
main.main()
	/Users/vsi/work/src/github.com/attic-labs/noms/samples/go/csv/csv-import/importer.go:158 +0xb8f
```

BOOM!

The problem appears to be related to improper quoting of strings in the second line of the exported CSV:

```sh
> head -n 2 /tmp/film-locations.csv
Actor1,Actor2,Actor3,Director,Distributor,FunFacts,Locations,ProductionCompany,ReleaseYear,Title,Writer
Siddarth,Nithya Menon,Priya Anand,Jayendra,,,Epic Roasthouse (399 Embarcadero),SPI Cinemas,2011,180,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba "

# Should probably be:

"Actor1","Actor2","Actor3","Director","Distributor","FunFacts","Locations","ProductionCompany","ReleaseYear","Title","Writer"
"Siddarth,Nithya","Menon,Priya","Anand,Jayendra",,,"Epic Roasthouse (399 Embarcadero)","SPI Cinemas",2011,180,"Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba "
```

A trivial test importing and re-exporting a simple CSV shows that the export utility does the right thing *some* of the time. But unfortunately there appears to be a condition in the sample dataset that breaks it and causes the CLI tour to barf.

**Comment by aboodman** [comment]
@vsivsi - thanks for the report. It looks like there's a number in the exported data with stray space at the beginning. I'm not sure if the export is broken, or if the data changed in a way that surprised us.

Will take a look tonight.

**Comment by aboodman** [comment]
@vsivsi - this has been fixed now. The ordering of the columns changed and this doc was not updated to match. I just changed the import command from:

```
csv-import --column-types=String,String,String,String,String,String,String,Number,String,String,String  /tmp/film-locations.csv /tmp/noms::films
```

to:

```
csv-import --column-types=String,String,String,String,String,String,String,String,Number,String,String  /tmp/film-locations.csv /tmp/noms::films
```

(note position of number column)

Apologies!

It sounded like you hit some other issues exporting and importing your own CSVs. Can you please give an example?

**Comment by vsivsi** [comment]
@aboodman  Thanks for your response. 

Ah yes, I see, I got fooled by the single word names "Siddarth" and "Jayendra" in that first row. A quick [Wikipedia search](https://en.wikipedia.org/wiki/180_(2011_Indian_film)) would have cleared that up! 😄 

The only other issue I see with the CLI tour now is that this line doesn't work as expected: 

```sh
> noms show 'http://demo.noms.io/cli-tour::#pckdvpvr9br1fie6c3pjudrlthe7na18'
Object not found: http://demo.noms.io/cli-tour::#pckdvpvr9br1fie6c3pjudrlthe7na18
```

This is presumably because the database has been rebuilt and this is no longer a valid commit.

Just using the dataset name or the current head commit both work fine.

```sh
> noms show 'http://demo.noms.io/cli-tour::sf-film-locations'
struct Commit {
  meta: struct Meta {
    date: String,
    inputPath: String,
  },
.
.
.

> 'http://demo.noms.io/cli-tour::#1a2aj8svslsu7g8hplsva6oq6iq3ib6c'
struct Commit {
  meta: struct Meta {
    date: String,
    inputPath: String,
  },
.
.
.
```
