### ISSUE TITLE
Syncing chi-building-violations failed commit validation

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#2598]
Sadness... (I was testing @ehalpern's magic new sync byte estimation patch),

```
noms sync http://demo.noms.io/cli-tour::chi-building-violations /Users/rafael/noms::chi-building-violations
        Error Trace:    /s)panic: 
	Error:		Attempted to write Value containing Ref to non-existent object.
	Messages:	upr8j2buesom8hl0tbgh1ftabok4mjt1
, contains ref hhqocaa4n9kksjl1qgeiup4ktslgi2tt, which points to a non-existent Value.
 [recovered]
        Error Trace:    
	Error:		Attempted to write Value containing Ref to non-existent object.
	Messages:	upr8j2buesom8hl0tbgh1ftabok4mjt1
, contains ref hhqocaa4n9kksjl1qgeiup4ktslgi2tt, which points to a non-existent Value.
```

the head of chi-building-violations is at: `ee5t6b0lr8g7h8f66chn18s9p4rg7b2c`

**Comment by rafael-atticlabs** [comment]
note that

`noms show http://demo.noms.io/cli-tour::#hhqocaa4n9kksjl1qgeiup4ktslgi2tt`
`noms show http://demo.noms.io/cli-tour::#hhqocaa4n9kksjl1qgeiup4ktslgi2tt`

both say the object can't be found.

This is almost certainly another instance of the validatity checker computing a different type hash. =-(.

**Comment by rafael-atticlabs** [comment]
A similar bug report from Ben Laurie at DeepMind contained the stack trace:

```
$ ./noms sync http://demo.noms.io/cli-tour::nyvr-model-year-index
ldb:/tmp/noms::nvr-index

        Error Trace:    B/s)panic:

Error: Attempted to write Value containing Ref to non-existent object.

Messages: 9s2n2bk8353ful1u8rko967po5e083tc

, contains ref bpl2iouhrculvicvmddvad9qn81h3649, which points to a
non-existent Value.

 [recovered]

        Error Trace:

Error: Attempted to write Value containing Ref to non-existent object.

Messages: 9s2n2bk8353ful1u8rko967po5e083tc

, contains ref bpl2iouhrculvicvmddvad9qn81h3649, which points to a
non-existent Value.



goroutine 1 [running]:

panic(0x4eaaa0, 0xc861464540)

/usr/local/go/src/runtime/panic.go:464 +0x3e6

github.com/attic-labs/noms/go/d.recoverWrappedTypes(0xc8554e7a38, 0x0, 0x0, 0x0)

/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/go/d/try.go:160
+0xf2

panic(0x4eaaa0, 0xc861464540)

/usr/local/go/src/runtime/panic.go:426 +0x4e9

github.com/attic-labs/noms/go/d.panicker.Errorf(0x79a860, 0x30,
0xc84e7d8640, 0x4, 0x4)

/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/go/d/try.go:25
+0x9e

github.com/attic-labs/noms/go/d.(*panicker).Errorf(0xa3a7d8, 0x79a860,
0x30, 0xc84e7d8640, 0x4, 0x4)

<autogenerated>:2 +0xbf

github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.Fail(0xb701e8,
0xa3a7d8, 0x7a8ca0, 0x3f, 0xc8554e7098, 0x3, 0x3, 0xac0f045cc1f99884)

/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertions.go:219
+0x34d

github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.(*Assertions).Fail(0xc820010620,
0x7a8ca0, 0x3f, 0xc8554e7098, 0x3, 0x3, 0xe03a7)

/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertion_forward.go:101
+0x5f

github.com/attic-labs/noms/go/types.(*ValueStore).checkChunksInCache(0xc832cd6140,
0xb7b738, 0xc8507d2760, 0xc84e7d8200, 0xc8507d2840)

/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/go/types/value_store.go:205
+0x9e1

github.com/attic-labs/noms/go/types.(*ValueStore).chunkHintsFromCache(0xc832cd6140,
0xb7b738, 0xc8507d2760, 0xac0f045c)

/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/go/types/value_store.go:175
+0x3a

github.com/attic-labs/noms/go/types.(*ValueStore).WriteValue(0xc832cd6140,
0xb7b738, 0xc8507d2760, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)

/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/go/types/value_store.go:118
+0x267

github.com/attic-labs/noms/go/datas.(*databaseCommon).tryUpdateRoot(0xc828469a90,
0xb7b880, 0xc84e7d8280, 0xc8507d26a0, 0x1e0d6deed22d6032,
0x2a4699089cab6ab0, 0xc8ab1d502c, 0x0, 0x0)

/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/go/datas/database_common.go:169
+0xcd

github.com/attic-labs/noms/go/datas.(*databaseCommon).doCommit(0xc828469a90,
0x7fff5fbffcdf, 0x9, 0xc84a744ea0, 0x3, 0x3, 0xc8201776c0,
0xc8517a6060, 0x0, 0x0)

/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/go/datas/database_common.go:123
+0x809

github.com/attic-labs/noms/go/datas.(*LocalDatabase).Commit(0xc828469a90,
0x7fff5fbffcdf, 0x9, 0xc84a744ea0, 0x3, 0x3, 0xc8201776c0,
0xc8517a6060, 0x0, 0x0, ...)

/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/go/datas/local_database.go:28
+0xba

github.com/attic-labs/noms/go/dataset.(*Dataset).FastForward(0xc8554e7c00,
0x8143ce9f6bc612b6, 0xf0b9ab89924f1dba, 0x49610665, 0x5, 0xc820177d00,
0xc82a90c020, 0x0, 0x0, 0x0, ...)

/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/go/dataset/dataset.go:124
+0x34b

main.runSync.func2()

/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/cmd/noms/noms_sync.go:90
+0x128

github.com/attic-labs/noms/go/d.Try(0xc8554e7d30, 0x0, 0x0, 0x0, 0x0, 0x0)

/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/go/d/try.go:69
+0x7e

main.runSync(0xc8200c5fa0, 0x2, 0x2, 0x0)

/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/cmd/noms/noms_sync.go:96
+0x51b

main.main()

/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/cmd/noms/noms.go:75
+0x536
```

Looking at this, it appears to have failed writing the root datasets map. If it's the same bug as above, it would explain why the referring object isn't contained in the database. I wonder if this is related to pre-existing datasets being in the database (i.e. maybe chunking of the root dataset)

**Comment by rafael-atticlabs** [comment]
Yup. I was able to repro exactly once, by:

- Using counter to a dataset.
- Using sync to create about 200 datasets which contain that data (such that I could see with splore that the root dataset had chunked)
- Sync the `chi-building-violations` dataset *into* that database.

Simply repeating the last sync *did not* fail again. It reported that all chunks were present in the target and then succeeded.

**Comment by ehalpern** [comment]
@rafael-atticlabs: I just inadvertently came upon this with a simpler case: sync'ing a second dataset to an ldb store.

The following produces the problem with all the datasets I've tried (see stack trace at bottom):

```
rm -r /tmp/noms    # start fresh
noms sync http://demo.noms.io/cli-tour::sf-film-locations ldb:/tmp/noms::film
noms sync http://demo.noms.io/cli-tour::sf-bike-parking ldb:/tmp/noms::bikes
``` 

The problem, doesn't seem to occur when I use an http server as in: 

```
rm -r /tmp/noms    # start fresh
noms serve ldb:/tmp/noms
noms sync http://demo.noms.io/cli-tour::sf-film-locations http://localhost:8000::film
noms sync http://demo.noms.io/cli-tour::sf-bike-parking http://localhost:8000::bikes
``` 

Do you think this is related to the fix to #1998?

Here's stacktrace:
```
goroutine 1 [running]:panic(0x46d280, 0xc42a5a8140)
       	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1github.com/attic-labs/noms/go/d.recoverWrappedTypes(0xc428de9b08, 0x0, 0x0, 0x0)
       	/Users/ehalpern/go/src/github.com/attic-labs/noms/go/d/try.go:160 +0x2b3panic(0x46d280, 0xc42a5a8140)
       	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:458 +0x243github.com/attic-labs/noms/go/d.panicker.Errorf(0x528c60, 0x30, 0xc42000d240, 0x4, 0x4)
       	/Users/ehalpern/go/src/github.com/attic-labs/noms/go/d/try.go:25 +0xa6github.com/attic-labs/noms/go/d.(*panicker).Errorf(0x791b48, 0x528c60, 0x30, 0xc42000d240, 0x4, 0x4)
       	<autogenerated>:2 +0x7egithub.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.Fail(0x74e000, 0x791b48, 0x52ba2d, 0x3f, 0xc428de91d8, 0x3, 0x3, 0xc4201870b8)
       	/Users/ehalpern/go/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertions.go:219 +0x2e5github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.(*Assertions).Fail(0xc420076550, 0x52ba2d, 0x3f, 0xc428de91d8, 0x3, 0x3, 0xc4200bde00)
       	/Users/ehalpern/go/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertion_forward.go:101 +0x69github.com/attic-labs/noms/go/types.(*ValueStore).checkChunksInCache(0xc420014a50, 0x756e80, 0xc42a463b40, 0x0, 0x0)
       	/Users/ehalpern/go/src/github.com/attic-labs/noms/go/types/value_store.go:205 +0x760github.com/attic-labs/noms/go/types.(*ValueStore).chunkHintsFromCache(0xc420014a50, 0x756e80, 0xc42a463b40, 0x53a6c7c9)
       	/Users/ehalpern/go/src/github.com/attic-labs/noms/go/types/value_store.go:175 +0x44github.com/attic-labs/noms/go/types.(*ValueStore).WriteValue(0xc420014a50, 0x756e80, 0xc42a463b40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
       	/Users/ehalpern/go/src/github.com/attic-labs/noms/go/types/value_store.go:118 +0x298github.com/attic-labs/noms/go/datas.(*databaseCommon).tryUpdateRoot(0xc4200acd20, 0x758080, 0xc42000cd00, 0xc42a463b20, 0x631c4cb7fdebde5e, 0x28dda7b23b0986bc, 0xc4659ab615, 0x758080, 0xc42000cd00)
       	/Users/ehalpern/go/src/github.com/attic-labs/noms/go/datas/database_common.go:169 +0xa4github.com/attic-labs/noms/go/datas.(*databaseCommon).doCommit(0xc4200acd20, 0xc420188762, 0xf, 0xc428e50a80, 0x3, 0x3, 0xc4200bde00, 0xc42a462a60, 0x3, 0xc4200bde00)
       	/Users/ehalpern/go/src/github.com/attic-labs/noms/go/datas/database_common.go:123 +0x482github.com/attic-labs/noms/go/datas.(*LocalDatabase).Commit(0xc4200acd20, 0xc420188762, 0xf, 0xc428e50a80, 0x3, 0x3, 0xc4200bde00, 0xc42a462a60, 0x3, 0x3, ...)
       	/Users/ehalpern/go/src/github.com/attic-labs/noms/go/datas/local_database.go:28 +0x89github.com/attic-labs/noms/go/dataset.(*Dataset).FastForward(0xc428de9c70, 0xd765e6dc82e0e5bd, 0x5f8499c74562cdcc, 0x9cc91bc6, 0x2, 0xc4200bde40, 0xc4283b3520, 0xc4200bde40, 0xc4283b3520, 0x200, ...)
       	/Users/ehalpern/go/src/github.com/attic-labs/noms/go/dataset/dataset.go:124 +0x287main.runSync.func2()
       	/Users/ehalpern/go/src/github.com/attic-labs/noms/cmd/noms/noms_sync.go:90 +0x140github.com/attic-labs/noms/go/d.Try(0xc428de9da0, 0x0, 0x0, 0x0, 0x0, 0x0)
       	/Users/ehalpern/go/src/github.com/attic-labs/noms/go/d/try.go:69 +0x8amain.runSync(0xc420101e40, 0x2, 0x2, 0x0)
       	/Users/ehalpern/go/src/github.com/attic-labs/noms/cmd/noms/noms_sync.go:96 +0x41amain.main()
       	/Users/ehalpern/go/src/github.com/attic-labs/noms/cmd/noms/noms.go:75 +0x438
```

**Comment by ehalpern** [comment]
For sanity, I've confirmed that the sync quantity [fix](https://github.com/attic-labs/noms/commit/27cbfdd489439cdce425e70a95c83f4ea4f42b34) did not introduce the problem by repro'ing it with the prior commit. Haven't searched back further yet.

**Comment by rafael-atticlabs** [comment]
I'm 99% sure the cause is here:

https://github.com/attic-labs/noms/blob/master/go/datas/local_database.go#L44

During sync, the db replaces its ValueStore, and that causes it to drop some hints on the floor. In the case of syncing into a db with a root datasets map which has chunked, refs to existing heads may have been read and thus stored as valid refs in the hintmap.

cc: @cmasone-attic
