### ISSUE TITLE
Error: SizeCache is missing expected value

### ISSUE THREAD

**Issue by ahl** [attic-labs/noms#2663]
Here's what I saw:

```
        Error Trace:    try.go:100
			try.go:59
			size_cache.go:70
			value_store.go:91
			ref.go:50
			meta_sequence.go:39
			meta_sequence.go:148
	Error:		SizeCache is missing expected value


goroutine 109 [running]:
panic(0x73ec80, 0xc423f18460)
	/opt/local/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/attic-labs/noms/go/d.PanicIfFalse(0x6ff400, 0xc421d671f8, 0x1, 0x1)
	/Users/ahl/gosrc/src/github.com/attic-labs/noms/go/d/try.go:59 +0xb3
github.com/attic-labs/noms/go/util/sizecache.(*SizeCache).Add(0xc4201ae050, 0x74cfa0, 0xc423f18280, 0x57cf, 0x771080, 0xc423f18200)
	/Users/ahl/gosrc/src/github.com/attic-labs/noms/go/util/sizecache/size_cache.go:70 +0x2e1
github.com/attic-labs/noms/go/types.(*ValueStore).ReadValue(0xc4201ae0a0, 0x4da75686a23f4939, 0x980c094f74beccb0, 0xc49631e92b, 0x4c6cd8, 0x41448b0c80000000)
	/Users/ahl/gosrc/src/github.com/attic-labs/noms/go/types/value_store.go:91 +0x3fa
github.com/attic-labs/noms/go/types.Ref.TargetValue(0x4da75686a23f4939, 0x980c094f74beccb0, 0x9631e92b, 0x3, 0xc4205b7980, 0xc4239c3780, 0x8fbaa0, 0xc4201ae0a0, 0x0, 0x0)
	/Users/ahl/gosrc/src/github.com/attic-labs/noms/go/types/ref.go:50 +0x45
github.com/attic-labs/noms/go/types.metaTuple.getChildSequence(0x4da75686a23f4939, 0x980c094f74beccb0, 0x9631e92b, 0x3, 0xc4205b7980, 0xc4239c3780, 0x1, 0x902100, 0xc4264526f8, 0x0, ...)
	/Users/ahl/gosrc/src/github.com/attic-labs/noms/go/types/meta_sequence.go:39 +0x9e
github.com/attic-labs/noms/go/types.metaSequence.getChildSequence(0xc422c00000, 0x1c8, 0x222, 0xc42046d600, 0x8fbaa0, 0xc4201ae0a0, 0x52, 0x9032c0, 0xc439758480)
	/Users/ahl/gosrc/src/github.com/attic-labs/noms/go/types/meta_sequence.go:148 +0xd1
github.com/attic-labs/noms/go/types.(*metaSequence).getChildSequence(0xc439758480, 0x52, 0x0, 0x0)
	<autogenerated>:237 +0x6d
github.com/attic-labs/noms/go/types.(*sequenceCursor).getChildSequence(0xc43b748e40, 0x1, 0x902100)
	/Users/ahl/gosrc/src/github.com/attic-labs/noms/go/types/sequence_cursor.go:41 +0x3d
github.com/attic-labs/noms/go/types.newCursorAt(0x9032c0, 0xc439758480, 0x1, 0x902100, 0xc445e44500, 0x0, 0x0, 0x0, 0xc4265c0000, 0xc439f07f80)
	/Users/ahl/gosrc/src/github.com/attic-labs/noms/go/types/ordered_sequences.go:64 +0x1ad
github.com/attic-labs/noms/go/types.newCursorAtValue(0x9032c0, 0xc42066f050, 0x902100, 0xc445e44500, 0xc43b740000, 0x19e)
	/Users/ahl/gosrc/src/github.com/attic-labs/noms/go/types/ordered_sequences.go:46 +0xb3
github.com/attic-labs/noms/go/types.Map.MaybeGet(0x9032c0, 0xc42066f050, 0xc4206ac8c0, 0x902100, 0xc445e44500, 0x1, 0x902d60, 0xc4265c4360)
	/Users/ahl/gosrc/src/github.com/attic-labs/noms/go/types/map.go:143 +0x5d
main.comments.func1(0x902100, 0xc445e44500, 0x19f)
	/Users/ahl/src/hn/organize/organize.go:308 +0x97
github.com/attic-labs/noms/go/types.List.IterAll.func1(0x737920, 0xc445e44500, 0x737920)
	/Users/ahl/gosrc/src/github.com/attic-labs/noms/go/types/list.go:230 +0x9d
github.com/attic-labs/noms/go/types.(*sequenceCursor).iter(0xc424e0c4e0, 0xc421d67b58)
	/Users/ahl/gosrc/src/github.com/attic-labs/noms/go/types/sequence_cursor.go:123 +0x68
github.com/attic-labs/noms/go/types.List.IterAll(0x902d60, 0xc4242608a0, 0xc424257ac0, 0xc421d67c40)
	/Users/ahl/gosrc/src/github.com/attic-labs/noms/go/types/list.go:233 +0x80
main.comments(0x902280, 0xc421d67e18, 0x9032c0, 0xc42066f050, 0xc4206ac8c0, 0x77c2fb, 0x5)
	/Users/ahl/src/hn/organize/organize.go:333 +0x292
main.makeStories.func1()
	/Users/ahl/src/hn/organize/organize.go:272 +0x79b
main.workerPool.func1(0xc4209fa840, 0xc42097fce0)
	/Users/ahl/src/hn/organize/organize.go:517 +0x27
created by main.workerPool
	/Users/ahl/src/hn/organize/organize.go:519 +0x7c
```

It's not reproducing for me, but it could be related to low memory.

**Comment by ahl** [comment]
... reproducing on a 52GB memory system; I don't think it's low memory...
