### ISSUE TITLE
Corrupt data in demo-server

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2695]
The following works fine against a fresh database, but it fails against `aa`.

```
cd $GOPATH/src/github.com/attic-labs/noms/samples/go/photo-index
go build
./photo-index --db=http://demo.noms.io/aa?access_token=xxx --out-ds=photos flickr/photos.value fb/photos.value
...
       Error Trace:    
	Error:		Version mismatch
	SDK version '7' is incompatible with data of version: ''
	HTTP Response: 504 (504 GATEWAY_TIMEOUT): 


goroutine 191 [running]:
panic(0x5be2a0, 0xc829334c40)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/attic-labs/noms/go/d.PanicIfError(0xaae028, 0xc829330f10)
	/Users/aa/src/github.com/attic-labs/noms/go/d/try.go:32 +0x6d
github.com/attic-labs/noms/go/datas.expectVersion(0xc8341a0c60)
	/Users/aa/src/github.com/attic-labs/noms/go/datas/http_batch_store.go:510 +0x440
github.com/attic-labs/noms/go/datas.(*httpBatchStore).sendWriteRequests.func1(0xc8200d3b90, 0xc82818e030, 0xc82818e000)
	/Users/aa/src/github.com/attic-labs/noms/go/datas/http_batch_store.go:402 +0x4eb
created by github.com/attic-labs/noms/go/datas.(*httpBatchStore).sendWriteRequests
	/Users/aa/src/github.com/attic-labs/noms/go/datas/http_batch_store.go:419 +0x91
```

There is a crash on the server too, it is:

```
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: error for request: /aa/writeValue/?access_token=xxx
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: server error: runtime error: invalid memory address or nil pointer dereference
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: goroutine 20 [running]:
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: runtime/debug.Stack(0x0, 0x0, 0x0)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/usr/local/go/src/runtime/debug/stack.go:24 +0x80
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: runtime/debug.PrintStack()
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/usr/local/go/src/runtime/debug/stack.go:16 +0x18
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: main.panicHandler(0x7f432de74370, 0xc824caeea0, 0xc82171fa40, 0x988a20, 0xc8200100d0)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/samples/go/demo-server/web_server.go:140 +0x1cf
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: github.com/attic-labs/noms/vendor/github.com/julienschmidt/httprouter.(*Router).recv(0xc8224100c0, 0x7f432de74370, 0xc824caeea0, 0xc82171fa40)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/vendor/github.com/julienschmidt/httprouter/router.go:273 +0x70
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: panic(0x988a20, 0xc8200100d0)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/usr/local/go/src/runtime/panic.go:426 +0x4e9
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: github.com/attic-labs/noms/go/d.recoverWrappedTypes(0xc82201d580, 0x0, 0x0, 0x0)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/go/d/try.go:160 +0xf2
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: panic(0x988a20, 0xc8200100d0)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/usr/local/go/src/runtime/panic.go:426 +0x4e9
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: github.com/attic-labs/noms/go/datas.handleWriteValue(0x7f432de74370, 0xc824caeea0, 0xc82171fa40, 0x7f432de28860, 0xc821abe7e0, 0x7f432de28800, 0xc823843c80)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/go/datas/remote_database_handlers.go:108 +0x4ac
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: github.com/attic-labs/noms/go/datas.versionCheck.func1.1()
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/go/datas/remote_database_handlers.go:74 +0x84
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: github.com/attic-labs/noms/go/d.Try(0xc82201d670, 0x0, 0x0, 0x0, 0x0, 0x0)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/go/d/try.go:69 +0x7e
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: github.com/attic-labs/noms/go/datas.versionCheck.func1(0x7f432de74370, 0xc824caeea0, 0xc82171fa40, 0x7f432de28860, 0xc821abe7e0, 0x7f432de28800, 0xc823843c80)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/go/datas/remote_database_handlers.go:74 +0x185
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: main.storeHandle.func1(0x7f432de74370, 0xc824caeea0, 0xc82171fa40, 0xc821abe720, 0x1, 0x1)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/samples/go/demo-server/web_server.go:90 +0x1b1
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: main.authorizeHandle.func1(0x7f432de74370, 0xc824caeea0, 0xc82171fa40, 0xc821abe720, 0x1, 0x1)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/samples/go/demo-server/web_server.go:116 +0x2d8
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: main.corsHandle.func1(0x7f432de74370, 0xc824caeea0, 0xc82171fa40, 0xc821abe720, 0x1, 0x1)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/samples/go/demo-server/web_server.go:133 +0x21e
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: main.notFound(0x7f432de74370, 0xc824caeea0, 0xc82171fa40)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/samples/go/demo-server/web_server.go:156 +0x48c
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: net/http.HandlerFunc.ServeHTTP(0xb51f68, 0x7f432de74370, 0xc824caeea0, 0xc82171fa40)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/usr/local/go/src/net/http/server.go:1618 +0x3a
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: github.com/attic-labs/noms/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc8224100c0, 0x7f432de74370, 0xc824caeea0, 0xc82171fa40)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/vendor/github.com/julienschmidt/httprouter/router.go:359 +0x390
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: main.startWebServer.func1(0x7f432de74370, 0xc824caeea0, 0xc82171fa40)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/var/lib/jenkins/workspace/DemoServer/src/github.com/attic-labs/noms/samples/go/demo-server/web_server.go:78 +0x41
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: net/http.HandlerFunc.ServeHTTP(0xb51f78, 0x7f432de74370, 0xc824caeea0, 0xc82171fa40)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/usr/local/go/src/net/http/server.go:1618 +0x3a
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: net/http.serverHandler.ServeHTTP(0xc8222f6000, 0x7f432de74370, 0xc824caeea0, 0xc82171fa40)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/usr/local/go/src/net/http/server.go:2081 +0x19e
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: net/http.(*conn).serve(0xc8200c0100)
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: #011/usr/local/go/src/net/http/server.go:1472 +0xf2e
Oct 12 04:36:38 ip-172-31-20-29 demo-server[25767]: created by net/http.(*Server).Serve
```

**Comment by aboodman** [comment]
cc: @kalman

**Comment by aboodman** [comment]
@cmasone-attic can you take a look? I could imagine that this is corrupt data that was created by previous bug and only thing to do is delete database. But seems worth investigating to be sure.

**Comment by aboodman** [comment]
Hm, actually same thing happening again on `aa2` now.

I wonder if this could be the result of a race. If you look at the crontab in demo-server we do have several jobs going at once. That is one difference between when this bug occurs and when I just run the commands locally and it doesn't occur.
