### ISSUE TITLE
noms show crash

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#2743]
I ran noms show on some data and it crashed. It doesn't repro unfortunately, I just got unlucky, but here you go:
```
> noms show 'http://demo.noms.io/aa2::repro/2742/family.value.byFace["Susan Boodman"][-1.292091147e+18]'
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x4e78fc34673e pc=0x1dcfb]

runtime stack:
runtime.throw(0x7a2320, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0xa2e720)
	/usr/local/go/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0xa2e720, 0x1, 0x25, 0x2193908)
	/usr/local/go/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7000035d0d40)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0xa2e720, 0x1, 0x10000000025, 0x1d99f)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0xa30a20, 0x0)
	/usr/local/go/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0xa30a20, 0x2193908)
	/usr/local/go/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0xb5ee10, 0xc800000025, 0x2193908)
	/usr/local/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc82001d500)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc828c6ff30 sp=0xc828c6ff28
runtime.mallocgc(0x800, 0x4f2200, 0x1f35453900000001, 0x35f760278554b4e6)
	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc828c70008 sp=0xc828c6ff30
runtime.newarray(0x4f2200, 0x800, 0x14)
	/usr/local/go/src/runtime/malloc.go:798 +0xc9 fp=0xc828c70048 sp=0xc828c70008
runtime.makeslice(0x4de940, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:32 +0x165 fp=0xc828c70098 sp=0xc828c70048
github.com/attic-labs/noms/go/types.generateOID(0xc820012a00, 0xc820011d00)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/type_cache.go:244 +0x41 fp=0xc828c70138 sp=0xc828c70098
github.com/attic-labs/noms/go/types.normalize.func1(0xc820012a00, 0xc82a3f8360, 0x4, 0x4)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/type_cache.go:198 +0x26 fp=0xc828c70150 sp=0xc828c70138
github.com/attic-labs/noms/go/types.walkType(0xc820012a00, 0xc82a3f8360, 0x4, 0x4, 0x7f80d0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/type_cache.go:229 +0xe6 fp=0xc828c70290 sp=0xc828c70150
github.com/attic-labs/noms/go/types.walkType(0xc8284767c0, 0xc82a3f8360, 0x3, 0x4, 0x7f80d0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/type_cache.go:238 +0x2ce fp=0xc828c703d0 sp=0xc828c70290
github.com/attic-labs/noms/go/types.walkType(0xc8285d0080, 0xc8296278a0, 0x2, 0x2, 0x7f80d0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/type_cache.go:238 +0x2ce fp=0xc828c70510 sp=0xc828c703d0
github.com/attic-labs/noms/go/types.walkType(0xc8286d5ac0, 0xc8296278a0, 0x2, 0x2, 0x7f80d0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/type_cache.go:234 +0x43e fp=0xc828c70650 sp=0xc828c70510
github.com/attic-labs/noms/go/types.walkType(0xc828730bc0, 0xc8296278a0, 0x2, 0x2, 0x7f80d0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/type_cache.go:234 +0x43e fp=0xc828c70790 sp=0xc828c70650
github.com/attic-labs/noms/go/types.walkType(0xc8288d09c0, 0xc828b708e8, 0x1, 0x1, 0x7f80d0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/type_cache.go:238 +0x2ce fp=0xc828c708d0 sp=0xc828c70790
github.com/attic-labs/noms/go/types.walkType(0xc828b93280, 0x0, 0x0, 0x0, 0x7f80d0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/type_cache.go:238 +0x2ce fp=0xc828c70a10 sp=0xc828c708d0
github.com/attic-labs/noms/go/types.normalize(0xc828b93280)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/type_cache.go:199 +0x42 fp=0xc828c70a40 sp=0xc828c70a10
github.com/attic-labs/noms/go/types.(*TypeCache).makeStructType(0xc8200c9140, 0xc828a62070, 0x6, 0xc8288ad4d0, 0x3, 0x3, 0xc8289e1de0, 0x3, 0x3, 0x1f627)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/type_cache.go:103 +0xad3 fp=0xc828c70c38 sp=0xc828c70a40
github.com/attic-labs/noms/go/types.(*valueDecoder).readStructType(0xc828c71318, 0x20409)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/value_decoder.go:213 +0x31f fp=0xc828c70d00 sp=0xc828c70c38
github.com/attic-labs/noms/go/types.(*valueDecoder).readType(0xc828c71318, 0x7)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/value_decoder.go:47 +0x3df fp=0xc828c70d78 sp=0xc828c70d00
github.com/attic-labs/noms/go/types.(*valueDecoder).readType(0xc828c71318, 0x13)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/value_decoder.go:43 +0x213 fp=0xc828c70df0 sp=0xc828c70d78
github.com/attic-labs/noms/go/types.(*valueDecoder).readUnionType(0xc828c71318, 0xc820012a0c)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/value_decoder.go:220 +0xa1 fp=0xc828c70e58 sp=0xc828c70df0
github.com/attic-labs/noms/go/types.(*valueDecoder).readType(0xc828c71318, 0xc820012a00)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/value_decoder.go:49 +0x45c fp=0xc828c70ed0 sp=0xc828c70e58
github.com/attic-labs/noms/go/types.(*valueDecoder).readType(0xc828c71318, 0xaaaaaaaaaaaaaa)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/value_decoder.go:41 +0x122 fp=0xc828c70f48 sp=0xc828c70ed0
github.com/attic-labs/noms/go/types.(*valueDecoder).readValue(0xc828c71318, 0x0, 0x0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/value_decoder.go:119 +0x50 fp=0xc828c712a8 sp=0xc828c70f48
github.com/attic-labs/noms/go/types.DecodeFromBytes(0xc828224000, 0xf1b3e, 0xf1b3e, 0xf801e8, 0xc8281d4060, 0xc8200c9140, 0x0, 0x0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/codec.go:35 +0x16a fp=0xc828c71348 sp=0xc828c712a8
github.com/attic-labs/noms/go/types.DecodeValue(0xda1ddcde63b99119, 0x1070c1d530aa0a3f, 0x8d393028, 0xc828224000, 0xf1b3e, 0xf1b3e, 0xf801e8, 0xc8281d4060, 0x0, 0x0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/codec.go:43 +0xf1 fp=0xc828c71480 sp=0xc828c71348
github.com/attic-labs/noms/go/types.(*ValueStore).ReadValue(0xc8281d4060, 0xda1ddcde63b99119, 0x1070c1d530aa0a3f, 0x8d393028, 0x0, 0x0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/value_store.go:90 +0x2d4 fp=0xc828c71670 sp=0xc828c71480
github.com/attic-labs/noms/go/datas.(*databaseCommon).datasetsFromRef(0xc8281ba440, 0xda1ddcde63b99119, 0x1070c1d530aa0a3f, 0xc88d393028, 0x10)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/datas/database_common.go:54 +0x54 fp=0xc828c716d8 sp=0xc828c71670
github.com/attic-labs/noms/go/datas.(*databaseCommon).Datasets(0xc8281ba440, 0x0, 0x0, 0x0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/datas/database_common.go:46 +0x1a1 fp=0xc828c71748 sp=0xc828c716d8
github.com/attic-labs/noms/go/datas.getDataset(0xf032e8, 0xc8281ba440, 0xc820018d99, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/datas/database_common.go:60 +0x1f4 fp=0xc828c718b8 sp=0xc828c71748
github.com/attic-labs/noms/go/datas.(*RemoteDatabaseClient).GetDataset(0xc8281ba440, 0xc820018d99, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/datas/remote_database_client.go:28 +0x88 fp=0xc828c71998 sp=0xc828c718b8
github.com/attic-labs/noms/go/spec.AbsolutePath.Resolve(0xc820018d99, 0x11, 0x0, 0x0, 0x0, 0xc820013500, 0x4, 0x4, 0xf032e8, 0xc8281ba440, ...)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/spec/absolute_path.go:74 +0x98 fp=0xc828c71ab0 sp=0xc828c71998
github.com/attic-labs/noms/go/spec.PathSpec.Value(0xc820018d80, 0x4, 0xc820018d85, 0x12, 0x0, 0x0, 0xc820018d99, 0x11, 0x0, 0x0, ...)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/spec/dataspec.go:230 +0xc6 fp=0xc828c71b18 sp=0xc828c71ab0
github.com/attic-labs/noms/go/spec.GetPath(0xc820018d80, 0x5a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/spec/dataspec.go:72 +0xff fp=0xc828c71c40 sp=0xc828c71b18
github.com/attic-labs/noms/go/config.(*Resolver).GetPath(0xc8200fc700, 0x7fff5fbff72a, 0x5a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/config/resolver.go:110 +0xd1 fp=0xc828c71ca8 sp=0xc828c71c40
main.runShow(0xc8200da990, 0x1, 0x1, 0x0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/cmd/noms/noms_show.go:38 +0x67 fp=0xc828c71d88 sp=0xc828c71ca8
main.main()
	/Users/kalman/src/go/src/github.com/attic-labs/noms/cmd/noms/noms.go:75 +0x536 fp=0xc828c71f30 sp=0xc828c71d88
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc828c71f80 sp=0xc828c71f30
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc828c71f88 sp=0xc828c71f80

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select]:
github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc820090380)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x29e
created by github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x270

goroutine 34 [select]:
github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc820016b00)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:69 +0x54d
created by github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x787

goroutine 35 [select]:
github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc820016b00)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:82 +0x14c
created by github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x7a9

goroutine 36 [select]:
github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc820016b00)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:768 +0x7e0
created by github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb/db.go:146 +0x9ad

goroutine 37 [select]:
github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc820016b00)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:715 +0x254
created by github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb/db.go:147 +0x9cf

goroutine 38 [select]:
github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc820016b00)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x1a3
created by github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/syndtr/goleveldb/leveldb/db.go:148 +0x9f1

goroutine 39 [select]:
github.com/attic-labs/noms/go/datas.(*httpBatchStore).batchReadRequests.func1(0xc8281bc070, 0xc820018ea0, 0xc8281c4320)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/datas/http_batch_store.go:155 +0x210
created by github.com/attic-labs/noms/go/datas.(*httpBatchStore).batchReadRequests
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/datas/http_batch_store.go:169 +0x64

goroutine 40 [select]:
github.com/attic-labs/noms/go/datas.(*httpBatchStore).batchReadRequests.func1(0xc8281bc070, 0xc820018f00, 0xc8281c4330)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/datas/http_batch_store.go:155 +0x210
created by github.com/attic-labs/noms/go/datas.(*httpBatchStore).batchReadRequests
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/datas/http_batch_store.go:169 +0x64

goroutine 41 [select]:
github.com/attic-labs/noms/go/datas.(*httpBatchStore).batchPutRequests.func1(0xc8281bc070)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/datas/http_batch_store.go:342 +0x3ca
created by github.com/attic-labs/noms/go/datas.(*httpBatchStore).batchPutRequests
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/datas/http_batch_store.go:366 +0x50

goroutine 50 [IO wait]:
net.runtime_pollWait(0xf03000, 0x72, 0xc820095000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200d2060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200d2060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200d2000, 0xc820095000, 0x1000, 0x1000, 0x0, 0xbae050, 0xc820010068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8281c6018, 0xc820095000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0xf030c0, 0xc8281c6018, 0xc8281d6138, 0xc820095000, 0x1000, 0x1000, 0x13933, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc8200c8a40, 0xc820095000, 0x1000, 0x1000, 0xc8281ffd1d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc8281d4480)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8281d4480, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8281d60d0)
	/usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 51 [select]:
net/http.(*persistConn).writeLoop(0xc8281d60d0)
	/usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:858 +0x10cb
```

@ahl @rafael-atticlabs @arv The crash spot looks like it's on line 244 of type_cache.go:
```
243 func generateOID(t *Type, allowUnresolvedCycles bool) {
244   buf := newBinaryNomsWriter()
245   encodeForOID(t, buf, allowUnresolvedCycles, t, nil)
246   oid := hash.FromData(buf.data())
247   t.oid = &oid
248 }
```

**Comment by kalman** [comment]
This may actually be a Go bug on Sierra. Lemme update.

**Comment by kalman** [comment]
I upgraded Go to 1.7.x and it's not happening anymore, so I'm putting it down to that, sorry :-)

Note: Go 1.6.x not happy with Sierra.
