### ISSUE TITLE
spec/GetDatabase() exposes panic in datas/http_batch_store.go at user level

### ISSUE THREAD

**Issue by jadrian** [attic-labs/noms#2864]
While attempting to resolve #2862 , I wrote the following test program:

```go
package main

import (
  "fmt"
  "os"
  "github.com/attic-labs/noms/go/spec"
)

func main() {
  sp, err := spec.ForDatabase("http://localhost:8000")
  if err != nil {
    fmt.Fprintf(os.Stderr, "Bad database spec: %s\n", err)
    return
  }
  sp.GetDatabase()
  defer sp.Close()
  fmt.Println("Exiting cleanly!")
}
```

If you run this program while running a local noms server, then it exits successfully with no output.  Without the noms server running, though, it produces a trace for a panic deep in the call stack:

```sh
> noms serve /tmp/noms-go-tour &
[1] 25570
Listening on port 8000...
> go run main.go
Exiting cleanly!
> kill 25570
[1]+  Done                    noms serve /tmp/noms-go-tour
> go run main.go
        Error Trace:
	Error:		Get http://localhost:8000/root/: dial tcp [::1]:8000: getsockopt: connection refused


goroutine 1 [running]:
panic(0x5999a0, 0xc8200102c0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:481 +0x3e6
github.com/attic-labs/noms/go/d.PanicIfError(0xac3b08, 0xc820075b30)
	/Users/jadrian/Documents/devel/go_workspace/src/github.com/attic-labs/noms/go/d/try.go:44 +0x6d
github.com/attic-labs/noms/go/datas.(*httpBatchStore).requestRoot(0xc82006a070, 0x6108b0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff08)
	/Users/jadrian/Documents/devel/go_workspace/src/github.com/attic-labs/noms/go/datas/http_batch_store.go:488 +0x583
github.com/attic-labs/noms/go/datas.(*httpBatchStore).Root(0xc82006a070, 0x0, 0x0, 0x0)
	/Users/jadrian/Documents/devel/go_workspace/src/github.com/attic-labs/noms/go/datas/http_batch_store.go:434 +0xa7
github.com/attic-labs/noms/go/datas.newDatabaseCommon(0xc8200820a0, 0xc820154060, 0xac29c8, 0xc82006a070, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jadrian/Documents/devel/go_workspace/src/github.com/attic-labs/noms/go/datas/database_common.go:31 +0x41
github.com/attic-labs/noms/go/datas.NewRemoteDatabase(0xc8200e9a00, 0x15, 0x0, 0x0, 0x1)
	/Users/jadrian/Documents/devel/go_workspace/src/github.com/attic-labs/noms/go/datas/remote_database_client.go:19 +0x3b9
github.com/attic-labs/noms/go/spec.Spec.createDatabase(0x679c40, 0x15, 0x679c40, 0x4, 0x679c45, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jadrian/Documents/devel/go_workspace/src/github.com/attic-labs/noms/go/spec/spec.go:246 +0x404
github.com/attic-labs/noms/go/spec.Spec.GetDatabase(0x679c40, 0x15, 0x679c40, 0x4, 0x679c45, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jadrian/Documents/devel/go_workspace/src/github.com/attic-labs/noms/go/spec/spec.go:145 +0x59
main.main()
	/Users/jadrian/Documents/devel/go_workspace/src/noms-tour/main.go:22 +0x20d
exit status 2
```

So this is a surprisingly easy panic to surface.  As it stands, the workaround for the example code is to `recover()` from the panic:

```go
func main() {
  sp, err := spec.ForDatabase("http://localhost:8000")
  if err != nil {
    fmt.Fprintf(os.Stderr, "Bad database spec: %s\n", err)
    return
  }
  defer func() {
    if err := recover(); err != nil {
      fmt.Fprintf(os.Stderr, "Could not connect to database '%s'\n", sp.Spec);
    }
  }()
  sp.GetDatabase()
  defer sp.Close()
  fmt.Println("Exiting cleanly!")
}
```

This produces the expected output...

```bash
> go run main.go
Could not connect to database 'http://localhost:8000'
```

... but per the guidelines on error reporting in [CONTRIBUTING.md](https://github.com/attic-labs/noms/blob/827c7050212e3be01cb1e22307a0d53ccb34edde/CONTRIBUTING.md#go-error-reporting), user-level code probably shouldn't have to "catch" panics to recover in a relatively conventional use case such as the server being unavailable.  It seems like some layer of this stack should be returning an error variable instead.

**Comment by cmasone-attic** [comment]
From the error reporting guidelines in CONTRIBUTING.md:

> For problems that might occur during correct processing, you can choose the Go-style of returned errors, or use the following to 'raise' a 'catchable' error (see go/d/try.go):
d.PanicIfError()
d.PanicIfTrue()
d.PanicIfFalse()

The code in question, having encountered an error that might occur during correct processing, used `d.PanicIfError()` to raise a catchable error. You should be doing this:
```go
err := d.Try(func() {
  sp, err := spec.ForDatabase("http://localhost:8000")
  sp.GetDatabase()
  defer sp.Close()
  fmt.Println("Exiting cleanly!")
})
if err != nil {
  fmt.Fprintf(os.Stderr, "Bad database spec: %s\n", err)
}
```

**Comment by aboodman** [comment]
It seems like since this is user-facing, it should use the comma-error idiom.
