### ISSUE TITLE
Second instance of `noms serve` panics

### ISSUE THREAD

**Issue by jadrian** [attic-labs/noms#2865]
If a Noms server is already running locally with ldb, then calling `noms serve` a second time produces a panic, even if the database paths are different.

```bash
> noms serve /tmp/noms-data &
[1] 25700
Listening on port 8000...
> noms serve /tmp/noms-data-2 &
[2] 25701
        Error Trace:
	Error:		Received unexpected error "listen tcp :8000: bind: address already in use"
 [recovered]
        Error Trace:
	Error:		Received unexpected error "listen tcp :8000: bind: address already in use"


goroutine 1 [running]:
panic(0x5054c0, 0xc821160520)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/attic-labs/noms/go/d.recoverWrappedTypes(0xc8200d9ce0, 0x0, 0x0, 0x0)
	/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/go/d/try.go:160 +0xf2
panic(0x5054c0, 0xc821160520)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/attic-labs/noms/go/d.panicker.Errorf(0x784b20, 0x21, 0xc82000bf20, 0x3, 0x3)
	/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/go/d/try.go:25 +0x9e
github.com/attic-labs/noms/go/d.(*panicker).Errorf(0xa6b8c8, 0x784b20, 0x21, 0xc82000bf20, 0x3, 0x3)
	<autogenerated>:1 +0xbf
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.Fail(0xba51c0, 0xa6b8c8, 0xc820014370, 0x4a, 0x0, 0x0, 0x0, 0xc821160348)
	/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertions.go:225 +0x5cb
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.NoError(0xba51c0, 0xa6b8c8, 0xd43200, 0xc8200141e0, 0x0, 0x0, 0x0, 0x1)
	/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertions.go:839 +0x18e
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.(*Assertions).NoError(0xc820012640, 0xd43200, 0xc8200141e0, 0x0, 0x0, 0x0, 0xd43200)
	/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertion_forward.go:205 +0x5f
github.com/attic-labs/noms/go/datas.(*RemoteDatabaseServer).Run(0xc8211640c0)
	/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/go/datas/database_server.go:51 +0x1f3
main.runServe.func2()
	/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/cmd/noms/noms_serve.go:65 +0x67
github.com/attic-labs/noms/go/d.Try(0xc8200d9d58, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/go/d/try.go:69 +0x7e
main.runServe(0xc8200d0ab0, 0x1, 0x1, 0x1)
	/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/cmd/noms/noms_serve.go:66 +0x2f3
main.main()
	/var/lib/jenkins/workspace/NomsBuildGoBinaries/src/github.com/attic-labs/noms/cmd/noms/noms.go:77 +0x536

[2]+  Exit 2                  noms serve /tmp/noms-data-2
```

It seems like this scenario should print an error message to the user, rather than a panic trace.

**Comment by rafael-atticlabs** [comment]
the first process is sitting on port 8000.

`noms serve --port=8001 /tmp/noms-data-2`

we could certainly use a better error message in this case.
