### ISSUE TITLE
noms sync failing for trivial syncs in some dbs

### ISSUE THREAD

**Issue by willhite** [attic-labs/noms#3031]
Syncing an existing dataset to a new dataset consistently fails on demo-server for certain databases.

```
$ noms sync jenna::#8hnotrbovoo1pjlmbhorfhiaob47es2f jenna::tmp2
        Error Trace:
	Error:		Version mismatch
	SDK version '7' is incompatible with data of version: ''
	HTTP Response: 502 (502 Bad Gateway): <html>
	<head><title>502 Bad Gateway</title></head>
	<body bgcolor="white">
	<center><h1>502 Bad Gateway</h1></center>
	<hr><center>nginx/1.10.1</center>
	</body>
	</html>
```

and then this in the demo-server log file:
```
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: Handling WriteValue from 127.0.0.1:58408
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: Wrote 1181 Kb as 0 chunks from 127.0.0.1:58408 in 167.409858ms
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: error for request: /p/jenstin/writeValue/?access_token=8A5Vd6mxpDo7YiALMs7eA6V4vkd6tV3niw1U0sJxHwtLRn2yjEcD9wR3FMU9OYZfaFON2z7c9FXjEpZZX62U0cGZjjYkWD4xyCa8CJZRCiwEprcdAqQP0fGos8oSfA2SZJ_flSu-92gHBKcaemqJ1Yf-T5ZSOFwRmslGDJvD9J7oeOJawXgox6SQV0hwZk10SsoUStDh28WD
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: server error: #015                        #015#011Error Trace:#011value_store.go:282
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: #015#011#011#011meta_sequence.go:130
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: #015#011Error:#011#011Attempted to write Value containing Ref to non-existent object.
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: #015#011Messages:#011m0ddu192e6g1oaq03d1c7f0brq0s5llj
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: , contains ref ue42obomm6fltr6n0d5l2nj97bls67jh, which points to a non-existent Value.
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: #015
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: panic: send on closed channel
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]:
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: goroutine 73628 [running]:
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: panic(0x8181a0, 0xc4251c44b0)
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.recoverToError(0xc42268d140)
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/remote_database_handlers.go:119 +0x11c
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.handleWriteValue.func3(0xc42268d140, 0xc42268d200, 0xaa3ec0, 0xc422eff520)
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/remote_database_handlers.go:153 +0xb8
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: created by github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.handleWriteValue
Jan  5 20:19:59 ip-172-31-20-29 demo-server[123068]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/remote_database_handlers.go:153 +0x332
```

See me if you want the command (with access tokens) to repro this.

**Comment by cmasone-attic** [comment]
Closed via 5447216
