### ISSUE TITLE
panic in remote_requests.ReadBatch.Close()

### ISSUE THREAD

**Issue by ehalpern** [attic-labs/noms#3063]
Encountered the following while running `attic cycle` talking to a local http server backed by nbs.
 
```
panic: sync: negative WaitGroup counter

goroutine 1481 [running]:
panic(0x5d33a0, 0xc42be42df0)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
sync.(*WaitGroup).Add(0xc42be42c00, 0xffffffffffffffff)
	/usr/local/Cellar/go/1.7.4/libexec/src/sync/waitgroup.go:75 +0x1fe
sync.(*WaitGroup).Done(0xc42be42c00)
	/usr/local/Cellar/go/1.7.4/libexec/src/sync/waitgroup.go:100 +0x34
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/chunks.OutstandingGetMany.Fail(0xc42be42c00, 0xc42bb16720)
	/Users/ehalpern/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/chunks/remote_requests.go:98 +0x2b
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/chunks.(*OutstandingGetMany).Fail(0xc42be42c20)
	<autogenerated>:178 +0x5b
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/chunks.(*ReadBatch).Close(0xc42be407b8, 0xffffffffffffffff, 0xc42ac607d0)
	/Users/ehalpern/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/chunks/remote_requests.go:118 +0xb5
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.(*httpBatchStore).sendReadRequests.func2.1(0xc420318280, 0xc42be42c10, 0xc42be407b8)
	/Users/ehalpern/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/http_batch_store.go:246 +0x4f
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.(*httpBatchStore).sendReadRequests.func2(0xc420318280, 0xc42be42c10, 0xc42be407b8, 0xc4201f2970, 0xc42be543f0)
	/Users/ehalpern/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/http_batch_store.go:251 +0xa7
created by github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.(*httpBatchStore).sendReadRequests
	/Users/ehalpern/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/http_batch_store.go:251 +0x234
```

**Comment by ehalpern** [comment]
@rafael-atticlabs, @cmasone-attic
