### ISSUE TITLE
Race condition in marshal.mapDecoder

### ISSUE THREAD

**Issue by ehalpern** [attic-labs/noms#3071]
I can repo this reliably running the new, more parallel, downloader job. Here's an example trace:
```
 downloader run http://localhost:8000::downloader/all/run '#bdojsm064oju1cc4243ljueto21pbjq5' --increment 100
Photo objects: 4, urls: 0, downloaded: 0, errors: 0, skipped: 1panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf4660]

goroutine 68 [running]:
panic(0x5b4120, 0xc4200140d0)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/marshal.Unmarshal.func1(0xc42044dc98)
	/Users/ehalpern/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/marshal/decode.go:73 +0x114
panic(0x5b4120, 0xc4200140d0)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:458 +0x243
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/marshal.mapDecoder.func1.1(0x995ba0, 0xc420441e30, 0x995ba0, 0xc4202c8c90)
	/Users/ehalpern/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/marshal/decode.go:480 +0x100
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.Map.IterAll.func1(0x5da220, 0xc420e1f600, 0x5da220)
	/Users/ehalpern/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/map.go:247 +0xad
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*sequenceCursor).iter(0xc420eee600, 0xc42044d900)
	/Users/ehalpern/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/sequence_cursor.go:209 +0x7c
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.Map.IterAll(0x996c20, 0xc420013fc0, 0xc420551ae0, 0xc42044d9b8)
	/Users/ehalpern/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/map.go:249 +0x95
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/marshal.mapDecoder.func1(0x9959c0, 0xc420551b00, 0x5bb760, 0xc420eee5d0, 0x195)
	/Users/ehalpern/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/marshal/decode.go:487 +0x1c6
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/marshal.structDecoder.func1(0x995ba0, 0xc42010f9e0, 0x5efb80, 0xc420eee5c0, 0x199)
	/Users/ehalpern/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/marshal/decode.go:322 +0x7aa
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/marshal.Unmarshal(0x995ba0, 0xc42010f9e0, 0x557ca0, 0xc420eee5c0, 0x0, 0x0)
	/Users/ehalpern/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/marshal/decode.go:84 +0x277
main.processDelta.func4(0xc42031e8d0, 0xc42000c3c0, 0xc42031e8c0, 0xc4203223b0, 0x996c20, 0xc4201d1e40, 0xc42028e360, 0x996ca0, 0xc4202847e0, 0xc420227cc0, ...)
	/Users/ehalpern/go/src/github.com/attic-labs/attic/go/jobs/downloader/downloader.go:292 +0x3c6
created by main.processDelta
	/Users/ehalpern/go/src/github.com/attic-labs/attic/go/jobs/downloader/downloader.go:310 +0x416
```

And here's the offending code:

```
func mapDecoder(t reflect.Type, tags nomsTags) decoderFunc {
	d := decoderCache.get(t)
	...

	var keyDecoder decoderFunc
	var valueDecoder decoderFunc

	d = func(v types.Value, rv reflect.Value) {
		...
		nomsMap.IterAll(func(k, v types.Value) {
			keyRv := reflect.New(t.Key()).Elem()
1 -->		keyDecoder(k, keyRv)
			valueRv := reflect.New(t.Elem()).Elem()
2 -->		valueDecoder(v, valueRv)
			...
		})
		...
	}

3-->decoderCache.set(t, d)
        keyDecoder = typeDecoder(t.Key(), nomsTags{})
        valueDecoder = typeDecoder(t.Elem(), nomsTags{})
	return d
}
```

The panic is occurs either at (1) or (2) depending on the run. Either keyDecoder or valueDecoder is nil. The race condition is at (3), which adds the decoder to the cache. This allows the decoder to escape before keyDecoder and typeDecoder are initialized.

We fixed a similar problem in the encoder last year #2852.

(The originating attic issue is here: https://github.com/attic-labs/attic/issues/527

**Comment by ehalpern** [comment]
@arv 
cc: @aboodman
