### ISSUE TITLE
Event-loop panics with Bad Request: Error: Can't set Root to a non-present Chunk

### ISSUE THREAD

**Issue by willhite** [attic-labs/noms#3084]
This is happening fairly frequently on demo-server2 but I believe that processes eventually manage to commit successfully and make progress... You can check out /var/log/attic-* on demo-server2 for more info.

```Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: panic: #015                        #015#011Error Trace:#011
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #015#011Error:#011#011Unexpected response: Bad Request: Error: Can't set Root to a non-present Chunk
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #015
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]:
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: goroutine 1 [running]:
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: panic(0x9caca0, 0xc44fbd1390)
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d.panicker.Errorf(0xad4968, 0x21, 0xc459626ab0, 0x3, 0x3)
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d/try.go:25 +0xa6
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d.(*panicker).Errorf(0xe608d8, 0xad4968, 0x21, 0xc459626ab0, 0x3, 0x3)
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #011<autogenerated>:1 +0x7e
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert.Fail(0xe1b200, 0xe608d8, 0xc4239a2550, 0x4f, 0x0, 0x0, 0x0, 0xc43976a000)
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert/assertions.go:225 +0x510
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert.(*Assertions).Fail(0xc420012730, 0xc4239a2550, 0x4f, 0x0, 0x0, 0x0, 0x4f)
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert/assertion_forward.go:101 +0x69
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.(*httpBatchStore).UpdateRoot(0xc458ad0580, 0xef231917f76b624b, 0xfc7215abd065dc1d, 0x3f2b9f37662dd535, 0x18002a4f8ac3035a, 0xcd03fc9ff29d6267, 0x300)
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/http_batch_store.go:457 +0x375
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.(*databaseCommon).tryUpdateRoot(0xc44da463c0, 0xe257e0, 0xc43d142900, 0xc421ef9860, 0x8ac3035a3f2b9f37, 0xf29d626718002a4f, 0xc4cd03fc9f, 0xe257e0, 0xc43d142900)
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/database_common.go:196 +0x169
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.(*databaseCommon).doCommit(0xc44da463c0, 0xac358a, 0x4, 0xc459626780, 0x3, 0x3, 0xc43f9e1980, 0xc420772ae0, 0x0, 0x0, ...)
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/database_common.go:145 +0x402
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.(*RemoteDatabaseClient).Commit(0xc44da463c0, 0xe266e0, 0xc44da463c0, 0xac358a, 0x4, 0x85d95f63a82a9e03, 0xddf76447d4f838f1, 0x88097fb4, 0x32d, 0xc46035c300, ...)
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/remote_database_client.go:34 +0x19b
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: github.com/attic-labs/attic/go/eventloop/loopdata.(*LoopData).Commit(0xc44a81ee10, 0x7fff2f0a2df3, 0x110, 0x7fff2f0a2df3, 0x5, 0x7fff2f0a2df9, 0x10a, 0x0, 0x0, 0x0, ...)
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #011/var/workspace/src/github.com/attic-labs/attic/go/eventloop/loopdata/loopdata.go:135 +0x2a6
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: github.com/attic-labs/attic/go/eventloop/loopdata.saveJobResult(0x7fff2f0a2df3, 0x110, 0x7fff2f0a2df3, 0x5, 0x7fff2f0a2df9, 0x10a, 0x0, 0x0, 0x0, 0x0, ...)
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #011/var/workspace/src/github.com/attic-labs/attic/go/eventloop/loopdata/jobexec.go:106 +0x532
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: github.com/attic-labs/attic/go/eventloop/loopdata.ExecuteCommand(0xc4512131e0, 0x7fff2f0a2df3, 0x110, 0x7fff2f0a2df3, 0x5, 0x7fff2f0a2df9, 0x10a, 0x0, 0x0, 0x0, ...)
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #011/var/workspace/src/github.com/attic-labs/attic/go/eventloop/loopdata/jobexec.go:87 +0x7e2
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: github.com/attic-labs/attic/go/eventloop/loopdata.(*EventLoop).ExecuteJob(0xc420183680, 0xc462f496e0, 0xac2fd5, 0x3, 0xc467238160, 0x155, 0x0, 0x0, 0x0, 0x0, ...)
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #011/var/workspace/src/github.com/attic-labs/attic/go/eventloop/loopdata/eventloop.go:342 +0xa2e
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: github.com/attic-labs/attic/go/eventloop/loopdata.(*EventLoop).TurnCrank(0xc420183680, 0x101)
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #011/var/workspace/src/github.com/attic-labs/attic/go/eventloop/loopdata/eventloop.go:96 +0x4c1
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: main.runLoop(0xc420147440, 0x1, 0x1, 0x0)
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #011/var/workspace/src/github.com/attic-labs/attic/cmd/attic/attic_loop.go:59 +0x33d
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: main.main()
Jan 19 00:08:58 ip-172-31-26-203 attic[70817]: #011/var/workspace/src/github.com/attic-labs/attic/cmd/attic/attic.go:66 +0x40c```

**Comment by aboodman** [comment]
I just observed this. Here is transcript:

```
$ noms sync 'aws://attic-internal-manifests:attic-internal-tables/admin::job-listing' 'https://db.attic.io/p/853806e4f742aa73390587a60b061022?access_token=g1JGEx5xMfItNG7vzAZ2DR2wiF_zq9s_As2CDs9fC75Hd3aVMCTaZlXPcPwz74coYf7Vt5xcthBreJ0whHnRg42krZxoVZEsqGNi8n7HksZZRGWWTxD_MC5qJbhRb2Hhv3GL3zA_X0u7JHohcncPFcMY92Gj7htd6oKAtxhA5a2X_SG17kRFeQdj0q7-EGzrxyp4v26J0CkE&id=76bf1b04f370982da83ab579954707c6::jl'
        Error Trace:    panic: 
	Error:		Unexpected response: Bad Request: Error: Can't set Root to a non-present Chunk
 [recovered]
        Error Trace:    
	Error:		Unexpected response: Bad Request: Error: Can't set Root to a non-present Chunk


goroutine 1 [running]:
panic(0x9f4160, 0xc420c24a60)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/attic-labs/noms/go/d.recoverWrappedTypes(0xc420625988, 0x0, 0x0, 0x0)
	/var/workspace/src/github.com/attic-labs/noms/go/d/try.go:159 +0x2b3
panic(0x9f4160, 0xc420c24a60)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/attic-labs/noms/go/d.panicker.Errorf(0xb03825, 0x21, 0xc42018fc20, 0x3, 0x3)
	/var/workspace/src/github.com/attic-labs/noms/go/d/try.go:25 +0xa6
github.com/attic-labs/noms/go/d.(*panicker).Errorf(0xe8dde0, 0xb03825, 0x21, 0xc42018fc20, 0x3, 0x3)
	<autogenerated>:1 +0x7e
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.Fail(0xe472e0, 0xe8dde0, 0xc42046c6e0, 0x4f, 0x0, 0x0, 0x0, 0xc4203680c0)
	/var/workspace/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertions.go:225 +0x510
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.(*Assertions).Fail(0xc420012620, 0xc42046c6e0, 0x4f, 0x0, 0x0, 0x0, 0x4f)
	/var/workspace/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertion_forward.go:101 +0x69
github.com/attic-labs/noms/go/datas.(*httpBatchStore).UpdateRoot(0xc420890c80, 0x73374e4a0e23fe0a, 0xc3a55747a748671, 0x8852607b3ee2aff4, 0x247caa2f88f2d69f, 0xcfbfad395bfb5ad7, 0x900)
	/var/workspace/src/github.com/attic-labs/noms/go/datas/http_batch_store.go:457 +0x375
github.com/attic-labs/noms/go/datas.(*databaseCommon).tryUpdateRoot(0xc420215c40, 0xe52340, 0xc42018f110, 0xc420ac7360, 0x88f2d69f8852607b, 0x5bfb5ad7247caa2f, 0xc4cfbfad39, 0xe52340, 0xc42018f110)
	/var/workspace/src/github.com/attic-labs/noms/go/datas/database_common.go:192 +0x17d
github.com/attic-labs/noms/go/datas.(*databaseCommon).doCommit(0xc420215c40, 0xc420ae84f6, 0x2, 0xc420411020, 0x3, 0x3, 0xc420473ac0, 0xc420428160, 0x0, 0x0, ...)
	/var/workspace/src/github.com/attic-labs/noms/go/datas/database_common.go:141 +0x432
github.com/attic-labs/noms/go/datas.(*databaseCommon).doFastForward(0xc420215c40, 0xe531c0, 0xc420215c40, 0xc420ae84f6, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/var/workspace/src/github.com/attic-labs/noms/go/datas/database_common.go:94 +0x298
github.com/attic-labs/noms/go/datas.(*RemoteDatabaseClient).FastForward(0xc420215c40, 0xe531c0, 0xc420215c40, 0xc420ae84f6, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/var/workspace/src/github.com/attic-labs/noms/go/datas/remote_database_client.go:53 +0xa7
main.runSync.func2()
	/var/workspace/src/github.com/attic-labs/noms/cmd/noms/noms_sync.go:92 +0x200
github.com/attic-labs/noms/go/d.Try(0xc420625d80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/workspace/src/github.com/attic-labs/noms/go/d/try.go:68 +0x8a
main.runSync(0xc420188c00, 0x2, 0x2, 0x0)
	/var/workspace/src/github.com/attic-labs/noms/cmd/noms/noms_sync.go:98 +0x543
main.main()
	/var/workspace/src/github.com/attic-labs/noms/cmd/noms/noms.go:77 +0x438
[ec2-user@ip-172-31-26-203 ~]$ 
[ec2-user@ip-172-31-26-203 ~]$ 
[ec2-user@ip-172-31-26-203 ~]$ 
[ec2-user@ip-172-31-26-203 ~]$ noms sync 'aws://attic-internal-manifests:attic-internal-tables/admin::job-listing' 'https://db.attic.io/p/853806e4f742aa73390587a60b061022?access_token=g1JGEx5xMfItNG7vzAZ2DR2wiF_zq9s_As2CDs9fC75Hd3aVMCTaZlXPcPwz74coYf7Vt5xcthBreJ0whHnRg42krZxoVZEsqGNi8n7HksZZRGWWTxD_MC5qJbhRb2Hhv3GL3zA_X0u7JHohcncPFcMY92Gj7htd6oKAtxhA5a2X_SG17kRFeQdj0q7-EGzrxyp4v26J0CkE&id=76bf1b04f370982da83ab579954707c6::jl'
All chunks already exist at destination! Created new dataset https://db.attic.io/p/853806e4f742aa73390587a60b061022?access_token=g1JGEx5xMfItNG7vzAZ2DR2wiF_zq9s_As2CDs9fC75Hd3aVMCTaZlXPcPwz74coYf7Vt5xcthBreJ0whHnRg42krZxoVZEsqGNi8n7HksZZRGWWTxD_MC5qJbhRb2Hhv3GL3zA_X0u7JHohcncPFcMY92Gj7htd6oKAtxhA5a2X_SG17kRFeQdj0q7-EGzrxyp4v26J0CkE&id=76bf1b04f370982da83ab579954707c6::jl.
```

**Comment by aboodman** [comment]
Log attached.
[log.txt](https://github.com/attic-labs/noms/files/733943/log.txt)
