### ISSUE TITLE
stacktrace when trying to update root map in some dbs

### ISSUE THREAD

**Issue by willhite** [attic-labs/noms#3131]
zane's db seems corrupted in some way, trying to delete a dataset or doing a noms sync results in a panic. This command:
```noms sync zane::account zane::test-ds```

results in this stacktrace:
```
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: error for request: /p/0f570f6b95f7692b18ddad2804489f89/writeValue/?access_token=jtSV6Lfhkp_cXNseOYzah_R12kLNiio2Fkr24AAjU3kEY7yiGX1E1-zidLX6q_-Rs2I52VVCxZCruxO345O5rsAETEPb6mh4-tK8y-T2wA9mHHonUjwHqPw_akV3XBatIFakcARbEl1Ijgl5OMwpbt6CGz2L8Qf3cXUnlz4NY0FSOouKenEpaGj3o95OLsI0ACutifZ3cc1T&id=d3ff409a71824bc589e49b88af309827
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: server error: #015                        #015#011Error Trace:#011dynamo_manifest.go:118
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #015#011Error:#011#011Received unexpected error "ValidationException: Item size has exceeded the maximum allowed size\n\tstatus code: 400, request id: C2GCTAQ3GTG5HERN17UUOFRJFBVV4KQNSO5AEMVJF66Q9ASUAAJG"
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #015
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: goroutine 12075923103 [running]:
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: runtime/debug.Stack(0x110, 0x0, 0x0)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/usr/local/go/src/runtime/debug/stack.go:24 +0x79
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: runtime/debug.PrintStack()
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/usr/local/go/src/runtime/debug/stack.go:16 +0x22
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: main.panicHandler(0xabde00, 0xc4327b7110, 0xc461bbd2c0, 0x807f40, 0xc47b147630)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/go/demo-server/web_server.go:181 +0x11b
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: github.com/attic-labs/attic/vendor/github.com/julienschmidt/httprouter.(*Router).recv(0xc420051cc0, 0xabde00, 0xc4327b7110, 0xc461bbd2c0)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/julienschmidt/httprouter/router.go:273 +0x6f
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: panic(0x807f40, 0xc47b147630)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/usr/local/go/src/runtime/panic.go:458 +0x243
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d.recoverWrappedTypes(0xc4616e9868, 0x0, 0x0, 0x0)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d/try.go:159 +0x2b3
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: panic(0x807f40, 0xc47b147630)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/usr/local/go/src/runtime/panic.go:458 +0x243
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d.panicker.Errorf(0x8b612d, 0x21, 0xc476797440, 0x3, 0x3)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d/try.go:25 +0xa6
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d.(*panicker).Errorf(0xafa410, 0x8b612d, 0x21, 0xc476797440, 0x3, 0x3)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011<autogenerated>:1 +0x7e
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert.Fail(0xab7f80, 0xafa410, 0xc42eefb2c0, 0xb6, 0x0, 0x0, 0x0, 0x0)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert/assertions.go:225 +0x510
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert.NoError(0xab7f80, 0xafa410, 0x7f357c486508, 0xc476797410, 0x0, 0x0, 0x0, 0x13)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert/assertions.go:839 +0x124
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert.(*Assertions).NoError(0xc420012660, 0x7f357c486508, 0xc476797410, 0x0, 0x0, 0x0, 0x63fb6)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert/assertion_forward.go:205 +0x69
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs.dynamoManifest.Update(0x7ffe62d4cc41, 0x17, 0xc44dbf43c5, 0x23, 0xabbbc0, 0xc488ee0140, 0xc49caa4000, 0x2da7, 0x2da7, 0x4ea6b83cdc49e2b1, ...)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs/dynamo_manifest.go:118 +0xb8a
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs.(*dynamoManifest).Update(0xc479a24a80, 0xc49caa4000, 0x2da7, 0x2da7, 0x4ea6b83cdc49e2b1, 0x6b34132df9013165, 0xdc49e2b187fbe5f3, 0xf90131654ea6b83c, 0x87fbe5f36b34132d, 0x0, ...)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011<autogenerated>:58 +0x10a
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs.(*NomsBlockStore).UpdateRoot(0xc45ec7adc0, 0x4ea6b83cdc49e2b1, 0x6b34132df9013165, 0xdc49e2b187fbe5f3, 0xf90131654ea6b83c, 0x87fbe5f36b34132d, 0xec9c2ca9d14e2f00)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs/store.go:293 +0x18e
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs.(*NomsBlockStore).Flush(0xc45ec7adc0)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs/store.go:326 +0xab
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*ValidatingBatchingSink).Flush(0xc43725e000, 0xc4a282d680, 0xc4616e9730, 0xec9c2c00)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/validating_batching_sink.go:110 +0xd4
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.handleWriteValue(0xabde00, 0xc4327b7110, 0xc461bbd2c0, 0xab9e80, 0xc4883b5ae0, 0xac16e0, 0xc45ec7adc0)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/remote_database_handlers.go:188 +0x98a
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.createHandler.func1.1()
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/remote_database_handlers.go:105 +0x67
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d.Try(0xc4616e9900, 0x0, 0x0, 0x0, 0x0, 0x0)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d/try.go:68 +0x8a
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.createHandler.func1(0xabde00, 0xc4327b7110, 0xc461bbd2c0, 0xab9e80, 0xc4883b5ae0, 0xac16e0, 0xc45ec7adc0)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/remote_database_handlers.go:105 +0x388
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: main.storeHandle.func1(0xabde00, 0xc4327b7110, 0xc461bbd2c0, 0xc49aba5580, 0x1, 0x1)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/go/demo-server/web_server.go:107 +0x1ad
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: main.authorizeHandle.func1(0xabde00, 0xc4327b7110, 0xc461bbd2c0, 0xc49aba5580, 0x1, 0x1)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/go/demo-server/web_server.go:121 +0xc0
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: main.corsHandle.func1(0xabde00, 0xc4327b7110, 0xc461bbd2c0, 0xc49aba5580, 0x1, 0x1)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/go/demo-server/web_server.go:174 +0x267
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: main.notFound(0xabde00, 0xc4327b7110, 0xc461bbd2c0)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/go/demo-server/web_server.go:197 +0x327
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: net/http.HandlerFunc.ServeHTTP(0x8f2278, 0xabde00, 0xc4327b7110, 0xc461bbd2c0)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/usr/local/go/src/net/http/server.go:1726 +0x44
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: github.com/attic-labs/attic/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc420051cc0, 0xabde00, 0xc4327b7110, 0xc461bbd2c0)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/julienschmidt/httprouter/router.go:359 +0x29e
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: main.startWebServer.func1(0xabde00, 0xc4327b7110, 0xc461bbd2c0)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/var/workspace/src/github.com/attic-labs/attic/go/demo-server/web_server.go:87 +0x4b
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: net/http.HandlerFunc.ServeHTTP(0x8f2288, 0xabde00, 0xc4327b7110, 0xc461bbd2c0)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/usr/local/go/src/net/http/server.go:1726 +0x44
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: net/http.serverHandler.ServeHTTP(0xc4200c4a00, 0xabde00, 0xc4327b7110, 0xc461bbd2c0)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/usr/local/go/src/net/http/server.go:2202 +0x7d
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: net/http.(*conn).serve(0xc4a0770780, 0xabe840, 0xc49b0cd200)
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/usr/local/go/src/net/http/server.go:1579 +0x4b7
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: created by net/http.(*Server).Serve
Jan 31 18:50:58 ip-172-31-26-203 demo-server[104138]: #011/usr/local/go/src/net/http/server.go:2293 +0x44d
Jan 31 18:51:01 ip-172-31-26-203 demo-server[104138]: Error decoding receipt for /p/0b45ffa92e6fd3f344b58ee8964affb6: Failed to decrypt receipt
```

**Comment by willhite** [comment]
@zane might have additional info

**Comment by zane** [comment]
Pretty sure you don't mean me. 😉

**Comment by willhite** [comment]
@zcstarr might have additional info

**Comment by cmasone-attic** [comment]
This is #3132. We discovered this yesterday and I've been working on the fix since then. There is no workaround.
