### ISSUE TITLE
noms sync crashes on closed file

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#3135]
It looks like noms sync is trying to write to a closed file. I've tried nbs and ldb and both crash with similar errors.

I'm sorry that I can't give an actual repro case, because the only up-to-date data we have is behind passwords (the public cli-tour stuff is an older protocol). This is the best I can do:
```bash
> noms sync 'https://db.attic.io/p/path/to::from' 'to'

        Error Trace:    /s)panic: 
	Error:		Received unexpected error "leveldb: closed"


goroutine 58634 [running]:
panic(0x5f4740, 0xc42cff2fc0)
	/opt/local/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/attic-labs/noms/go/d.panicker.Errorf(0x704511, 0x21, 0xc42cdd2a80, 0x3, 0x3)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/d/try.go:25 +0xa6
github.com/attic-labs/noms/go/d.(*panicker).Errorf(0xa8f9e8, 0x704511, 0x21, 0xc42cdd2a80, 0x3, 0x3)
	<autogenerated>:1 +0x7e
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.Fail(0xa49200, 0xa8f9e8, 0xc42cdd29f0, 0x2b, 0x0, 0x0, 0x0, 0x0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertions.go:225 +0x510
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.NoError(0xa49200, 0xa8f9e8, 0xa49180, 0xc420014dd0, 0x0, 0x0, 0x0, 0xc420014dd0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertions.go:839 +0x124
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.(*Assertions).NoError(0xc420014650, 0xa49180, 0xc420014dd0, 0x0, 0x0, 0x0, 0x0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertion_forward.go:205 +0x69
github.com/attic-labs/noms/go/chunks.(*internalLevelDBStore).getByKey(0xc4206f2040, 0xc430496280, 0x1b, 0x1b, 0x9e3ffb489fb28f56, 0xf64a8244dabdc828, 0xb164fd24, 0x0, 0x0, 0x0, ...)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/chunks/leveldb_store.go:229 +0x12b
github.com/attic-labs/noms/go/chunks.(*LevelDBStore).Get(0xc4202861e0, 0x9e3ffb489fb28f56, 0xf64a8244dabdc828, 0xb164fd24, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/chunks/leveldb_store.go:100 +0x1a5
github.com/attic-labs/noms/go/chunks.(*LevelDBStore).GetMany(0xc4202861e0, 0xc42cdd2150, 0xc420503f20)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/chunks/leveldb_store.go:105 +0xdf
github.com/attic-labs/noms/go/types.(*BatchStoreAdaptor).GetMany(0xc420467e00, 0xc42cdd2150, 0xc420503f20)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/batch_store.go:74 +0x76
github.com/attic-labs/noms/go/types.(*ValueStore).ReadManyValues.func3(0xc4203d19a0, 0xc42cdd2150, 0xc420503f20)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/value_store.go:213 +0x47
created by github.com/attic-labs/noms/go/types.(*ValueStore).ReadManyValues
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/types/value_store.go:213 +0x2b6
```

@rafael-atticlabs @cmasone-attic

**Comment by kalman** [comment]
NBS version:
```bash
> noms sync 'https://db.attic.io/p/path/to::from' nbs:./db::issues/714

        Error Trace:    /s)panic: 
	Error:		Received unexpected error "read db/ukaepuvlsaal2djsa4tdjuaabj70hgk4: bad file descriptor"


goroutine 59464 [running]:
panic(0x5f4740, 0xc473e7ce80)
	/opt/local/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/attic-labs/noms/go/d.panicker.Errorf(0x704511, 0x21, 0xc473e7bf20, 0x3, 0x3)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/d/try.go:25 +0xa6
github.com/attic-labs/noms/go/d.(*panicker).Errorf(0xa8f9e8, 0x704511, 0x21, 0xc473e7bf20, 0x3, 0x3)
	<autogenerated>:1 +0x7e
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.Fail(0xa49200, 0xa8f9e8, 0xc47360de60, 0x59, 0x0, 0x0, 0x0, 0x67df20)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertions.go:225 +0x510
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.NoError(0xa49200, 0xa8f9e8, 0xa4a880, 0xc473e7bef0, 0x0, 0x0, 0x0, 0xc473e7bef0)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertions.go:839 +0x124
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.(*Assertions).NoError(0xc420078550, 0xa4a880, 0xc473e7bef0, 0x0, 0x0, 0x0, 0xa4a880)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertion_forward.go:205 +0x69
github.com/attic-labs/noms/go/nbs.tableReader.readAtOffsets(0xd828, 0xc448e20000, 0xd828, 0xd828, 0xc44a1da000, 0xd828, 0xd828, 0xc449d14000, 0xd828, 0xd828, ...)
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/nbs/table_reader.go:231 +0x108
created by github.com/attic-labs/noms/go/nbs.tableReader.getMany
	/Users/kalman/src/go/src/github.com/attic-labs/noms/go/nbs/table_reader.go:284 +0x440
