### ISSUE TITLE
Log size of range request and request ID when AWS get fails

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#3206]
```Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: panic: #015                        #015#011Error Trace:#011try.go:99
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: #015#011#011#011try.go:44
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: #015#011#011#011s3_table_reader.go:52
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: #015#011#011#011s3_table_persister.go:30
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: #015#011Error:#011#011read tcp 172.31.26.203:52980->52.218.144.41:443: read: connection reset by peer
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: #015
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: 
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: goroutine 523897 [running]:
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: panic(0x8f6d40, 0xc5d7d7fac0)
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d.PanicIfError(0xba4a40, 0xc6343903c0)
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d/try.go:44 +0x74
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs.newS3TableReader(0xbacf80, 0xc5272782c0, 0x7ffc85fa4c55, 0x14, 0xc29eaaf1191532d3, 0x38afedf296cbe800, 0xa09fc28ea873, 0xc42005a260, 0xc42000d380, 0xc57bb7a870, ...)
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs/s3_table_reader.go:52 +0x539
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs.s3TablePersister.Open(0xbacf80, 0xc5272782c0, 0x7ffc85fa4c55, 0x14, 0x500000, 0xc42005a260, 0xc42000d380, 0xc29eaaf1191532d3, 0x38afedf296cbe800, 0xa09fc28ea873, ...)
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs/s3_table_persister.go:30 +0x8f
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs.(*s3TablePersister).Open(0xc43080dfc0, 0xc29eaaf1191532d3, 0x38afedf296cbe800, 0xa09fc28ea873, 0xc468b69620, 0x0)
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: #011<autogenerated>:136 +0x8d
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs.tableSet.Rebase.func1(0xc45a2b8000, 0x4e, 0x4e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xbaad00, ...)
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs/table_set.go:253 +0x60
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: created by github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs.tableSet.Rebase
Feb 19 01:02:02 ip-172-31-26-203 demo-server[83418]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs/table_set.go:255 +0x7fc
```

We should see if we can log the size of the range request that fails

**Comment by cmasone-attic** [comment]
Fixed this a while back, but now I want to log the request ID as well.
FYI @zcstarr ... are there other issues that track the s3_table_reader stuff as well? I want to merge them all
