### ISSUE TITLE
Assert failure in `ValueStore.bufferChunk`

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3371]
```
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: panic: 
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: #015                          #015#011Error Trace:#011value_store.go:256
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #015#011            #011#015#011#011#011ref.go:78
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #015#011Error:      #011Should be false
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: 
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: 
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: goroutine 138 [running]:
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: panic(0x908160, 0xc44b4b5f40)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d.panicker.Errorf(0xc42283a080, 0x79, 0x0, 0x0, 0x0)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d/try.go:25 +0xa6
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d.(*panicker).Errorf(0xc95f28, 0xc42283a080, 0x79, 0x0, 0x0, 0x0)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011<autogenerated>:1 +0x7e
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert.Fail(0xc4f120, 0xc95f28, 0x9ce2b8, 0xf, 0x0, 0x0, 0x0, 0x35487c28e5d73897)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert/assertions.go:226 +0x216
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert.False(0xc4f120, 0xc95f28, 0x35487c28e5d73801, 0x0, 0x0, 0x0, 0x8c6e40)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert/assertions.go:550 +0x75
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert.(*Assertions).False
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: (0xc420012690, 0xc420205901, 0x0, 0x0, 0x0, 0xc4df214d01)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert/assertion_forward.go:107 +0x5e
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*ValueStore).bufferChunk.func2(0xabc52204256fa485, 0x9122912289a9b218, 0xaec21d3d, 0xc4200fbc40, 0x2, 0xc4788eace0)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/value_store.go:256 +0x2ef
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.Ref.WalkRefs(0xabc52204256fa485, 0x9122912289a9b218, 0xaec21d3d, 0xc4200fbc40, 0x2, 0xc4788eace0, 0xc4e66a6d40)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/ref.go:78 +0x42
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*Ref).WalkRefs(0xc450014ae0, 0xc4e66a6d40)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011<autogenerated>:18 +0x6d
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.Struct.WalkRefs(0xc4498bbd85, 0x9, 0xc4788eac80, 0x2, 0x2, 0xc4788eacc0, 0x2, 0x2, 0xc4788ead60, 0xc4e66a6d40)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/struct.go:98 +0x5b
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*Struct).WalkRefs(0xc4b2d4a910, 0xc4e66a6d40)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011<autogenerated>:
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: 176 +0x78
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.setLeafSequence.WalkRefs(0xc53820, 0xc42020e460, 0x4, 0x8, 0xc4eca45000, 0x4, 0x4, 0xc4e66a6d40)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/set_leaf_sequence.go:24 +
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: 0x58
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*setLeafSequence).WalkRefs(0xc4eca45040, 0xc4e66a6d40)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011<autogenerated>:162 +0x78
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.Set.WalkRefs(0xc5a6a0, 0xc4eca45040, 0xc4788eb040, 0xc4e66a6d40)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/set.go:
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: 117 +0x3b
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*Set).WalkRefs(0xc4788eb060, 0xc4e66a6d40)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011<autogenerated>:343 +0x6e
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.Struct.WalkRefs(0xc4498bbd60, 0x5, 0xc4788eab80
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: , 0x2, 0x2, 0xc4788eabc0, 0x2, 0x2, 0xc4788eb080, 0xc4e66a6d40)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/struct.go:98 +0x5b
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: 
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*Struct).WalkRefs(0xc4b2d4ab40, 0xc4e66a6d40)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011<autogenerated>:176 +0x78
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.mapLeafSequence.WalkRefs
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: (0xc53820, 0xc42020e460, 0x10, 0x6, 0xc420ccce00, 0x10, 0x10, 0xc4e66a6d40)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/map_leaf_sequence.go:
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: 49 +0x93
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*mapLeafSequence).WalkRefs(0xc4e1fa1580, 0xc4e66a6d40)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011<autogenerated>:146 +0x78
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.Map.WalkRefs
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: (0xc5a5a0, 0xc4e1fa1580, 0xc4d531f5c0, 0xc4e66a6d40)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/map.go:134 +0x3b
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*Map).WalkRefs(
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: 0xc4d531f5e0, 0xc4e66a6d40)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011<autogenerated>:309 +0x6e
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*ValueStore).bufferChunk(0xc42020e460, 0xc59680, 0xc4d531f5e0
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: , 0xd0ac07a84e2ee7b6, 0x90e02a41403718d1, 0x76aef1e1, 0xc437ba0000, 0x1991, 0x2000, 0x5)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/value_store.go:263 +0x60a
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*ValueStore).WriteValue(0xc42020e460, 0xc59680, 
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: 0xc4d531f5e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/value_store.go:210 +
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: 0x3c1
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*valueEncoder).maybeWriteMetaSequence(0xc472ac4820, 0xc59f20, 0xc43abdb5f0, 0xc59f20)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: /var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/value_encoder.go:108 +0x562
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*valueEncoder).writeValue(0xc472ac4820, 0xc59680, 0xc42e50c920)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/value_encoder.go:153 +0x93d
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*valueEncoder).writeStruct(0xc472ac4820, 0x9c9bf8, 0x6
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: , 0xc4f2f9ddd0, 0x3, 0x3, 0xc4f2f9de00, 0x3, 0x3, 0xc427c563c0)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/value_encoder.go:190 +0x11b
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: 
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*valueEncoder).writeValue(0xc472ac4820, 0xc59860, 0xc4208400f0)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: /var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/value_encoder.go:172 +0xaaf
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.EncodeValue(0xc59860, 0xc4208400f0, 0xc4f2a0, 
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: 0xc42020e460, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/codec.go:
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: 20 +0x183
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*ValueStore).WriteValue(0xc42020e460, 0xc59860, 0xc4208400f0, 0x0, 0x0
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: thumbnailer/run: stderr: , 0x0, 0x0, 0x0, 0x0)
Apr  9 07:23:18 ip-172-31-31-70 attic[37836]: #011/var/workspace/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/value_store.go:201 +0xa1
```

**Comment by rafael-atticlabs** [comment]
FYI, @cmasone-attic. I don't think this is blocking anything right now. Just recording here so we don't loose it. Not sure how this could be happening.
