### ISSUE TITLE
Sync'ing a large dataset over http results in 400

### ISSUE THREAD

**Issue by ehalpern** [attic-labs/noms#3589]
```
export DB=http://bot.perf.attic.io:8000/p/tester0?access_token=u6xZzU7sQYXdThZKqv2bLl2XGbPnGWRzNRT4hP-r4rCvUfOypoVhQXut_V-WNupFH1iFmKGdUdLO87UbO2Em-qVBucIBz9HrX7oLwBL1VEUlvFDoh9cnGj20e650aY6RyQbmae4dzDFEXkLRdM5s4tRgu6rtqX0zD9LzX6pKBKbUYftzegB25Zu6HVaoPgVbS2v_yQHsyWjh6n8Vk1Cb_A==
noms sync $DB::exiftractor/input nbs:/tmp/testdb::.
        Error Trace:    try.go:99
                    try.go:37
                    http_chunk_store.go:299
                    http_chunk_store.go:172
                    http_chunk_store.go:270
                    asm_amd64.s:2197
    Error:          Unexpected response: Bad Request


goroutine 50142 [running]:
github.com/attic-labs/noms/go/d.Panic(0xbbeb5c, 0x17, 0xc4286f1e70, 0x1, 0x1)
    /var/workspace/src/github.com/attic-labs/noms/go/d/try.go:37 +0x120
github.com/attic-labs/noms/go/datas.(*httpChunkStore).getRefs(0xc420168c60, 0xc42a1a4000)
    /var/workspace/src/github.com/attic-labs/noms/go/datas/http_chunk_store.go:299 +0x841
github.com/attic-labs/noms/go/datas.(*httpChunkStore).(github.com/attic-labs/noms/go/datas.getRefs)-fm(0xc42a1a4000)
    /var/workspace/src/github.com/attic-labs/noms/go/datas/http_chunk_store.go:172 +0x34
github.com/attic-labs/noms/go/datas.(*httpChunkStore).sendReadRequests.func2(0xc42000e028, 0xc4201d2f10, 0xc420168c60)
    /var/workspace/src/github.com/attic-labs/noms/go/datas/http_chunk_store.go:270 +0x5d
created by github.com/attic-labs/noms/go/datas.(*httpChunkStore).sendReadRequests
```

The server doesn't report an error by default.  Re-running with --verbose, the error is: 

```
Compacted table of 2 Kb in 97.040455ms
Returning bad request:
http: POST too large
```

**Comment by ehalpern** [comment]
Server error reporting is disabled unless --verbose is specified. 

With verbose enabled, the error is clear:
```
Compacted table of 2 Kb in 97.040455ms
Returning bad request:
http: POST too large
```

**Comment by ehalpern** [comment]
cc: @cmasone-attic, @rafael-atticlabs

**Comment by rafael-atticlabs** [comment]
That error comes from: https://github.com/attic-labs/noms/blob/master/go/datas/remote_database_handlers.go#L112, but it's swallowing the call stack of the original panic.

**Comment by ehalpern** [comment]
See updated summary and #3590

**Comment by ehalpern** [comment]
Summarizing: 
- The root cause is that httpChunkStore.getRefs is sending a POST body that's too large
- This problem is detected when parsing the form in [extractHashes](https://github.com/attic-labs/noms/blob/4e7db2cd49cf5da475e3f3c5b994e2a08e1dbd51/go/datas/remote_database_handlers.go#L312)
- The error is hidden behind verbose.Log in [createHandler](https://github.com/attic-labs/noms/blob/master/go/datas/remote_database_handlers.go#L112)
- The bug can be repro'ed locally by sync'ing a moderately sized dataset via http.

cc: @cmasone-attic, @rafael-atticlabs
